<?php
class CountryTableSeeder extends Seeder
{
    public function run()
    {   
        //DATOS 001_002_pais (es)
        DB::insert(DB::raw("INSERT INTO `001_002_country` (`id_002`, `lang_002`, `name_002`, `sorting_002`, `prefix_002`, `territorial_area_1_002`, `territorial_area_2_002`, `territorial_area_3_002`) VALUES
            ('AD', 'es', 'Andorra', 0, '00', NULL, NULL, NULL),
            ('AE', 'es', 'Emiratos Árabes Uníos',                                                       0, '00', NULL, NULL, NULL),
            ('AF', 'es', 'Afganistán',                                                                  0, '00', NULL, NULL, NULL),
            ('AG', 'es', 'Antigua y Barbuda',                                                           0, '00', NULL, NULL, NULL),
            ('AI', 'es', 'Anguila',                                                                     0, '00', NULL, NULL, NULL),
            ('AL', 'es', 'Albania',                                                                     0, '00', NULL, NULL, NULL),
            ('AM', 'es', 'Armenia',                                                                     0, '00', NULL, NULL, NULL),
            ('AN', 'es', 'Antillas Neerlandesas',                                                       0, '00', NULL, NULL, NULL),
            ('AO', 'es', 'Angola',                                                                      0, '00', NULL, NULL, NULL),
            ('AQ', 'es', 'Antártida',                                                                   0, '00', NULL, NULL, NULL),
            ('AR', 'es', 'Argentina',                                                                   0, '00', NULL, NULL, NULL),
            ('AS', 'es', 'Samoa Americana',                                                             0, '00', NULL, NULL, NULL),
            ('AT', 'es', 'Austria',                                                                     0, '00', NULL, NULL, NULL),
            ('AU', 'es', 'Australia',                                                                   0, '00', NULL, NULL, NULL),
            ('AW', 'es', 'Aruba',                                                                       0, '00', NULL, NULL, NULL),
            ('AX', 'es', 'Islas Åland',                                                                 0, '00', NULL, NULL, NULL),
            ('AZ', 'es', 'Azerbaiyán',                                                                  0, '00', NULL, NULL, NULL),
            ('BA', 'es', 'Bosnia-Herzegovina',                                                          0, '00', NULL, NULL, NULL),
            ('BB', 'es', 'Barbados',                                                                    0, '00', NULL, NULL, NULL),
            ('BD', 'es', 'Bangladesh',                                                                  0, '00', NULL, NULL, NULL),
            ('BE', 'es', 'Bélgica',                                                                     0, '00', NULL, NULL, NULL),
            ('BF', 'es', 'Burkina Faso',                                                                0, '00', NULL, NULL, NULL),
            ('BG', 'es', 'Bulgaria',                                                                    0, '00', NULL, NULL, NULL),
            ('BH', 'es', 'Bahréin',                                                                     0, '00', NULL, NULL, NULL),
            ('BI', 'es', 'Burundi',                                                                     0, '00', NULL, NULL, NULL),
            ('BJ', 'es', 'Benín',                                                                       0, '00', NULL, NULL, NULL),
            ('BL', 'es', 'San Bartolomé',                                                               0, '00', NULL, NULL, NULL),
            ('BM', 'es', 'Bermudas',                                                                    0, '00', NULL, NULL, NULL),
            ('BN', 'es', 'Brunéi',                                                                      0, '00', NULL, NULL, NULL),
            ('BO', 'es', 'Bolivia',                                                                     0, '00', NULL, NULL, NULL),
            ('BR', 'es', 'Brasil',                                                                      0, '00', NULL, NULL, NULL),
            ('BS', 'es', 'Bahamas',                                                                     0, '00', NULL, NULL, NULL),
            ('BT', 'es', 'Bután',                                                                       0, '00', NULL, NULL, NULL),
            ('BV', 'es', 'Isla Bouvet',                                                                 0, '00', NULL, NULL, NULL),
            ('BW', 'es', 'Botsuana',                                                                    0, '00', NULL, NULL, NULL),
            ('BY', 'es', 'Bielorrusia',                                                                 0, '00', NULL, NULL, NULL),
            ('BZ', 'es', 'Belice',                                                                      0, '00', NULL, NULL, NULL),
            ('CA', 'es', 'Canadá',                                                                      0, '00', 'Provincias', NULL, NULL),
            ('CC', 'es', 'Islas Cocos',                                                                 0, '00', NULL, NULL, NULL),
            ('CD', 'es', 'República Democrática del Congo',                                             0, '00', NULL, NULL, NULL),
            ('CF', 'es', 'República Centroafricana',                                                    0, '00', NULL, NULL, NULL),
            ('CG', 'es', 'Congo',                                                                       0, '00', NULL, NULL, NULL),
            ('CH', 'es', 'Suiza',                                                                       0, '00', NULL, NULL, NULL),
            ('CI', 'es', 'Costa de Marfil',                                                             0, '00', NULL, NULL, NULL),
            ('CK', 'es', 'Islas Cook',                                                                  0, '00', NULL, NULL, NULL),
            ('CL', 'es', 'Chile',                                                                       0, '00', NULL, NULL, NULL),
            ('CM', 'es', 'Camerún',                                                                     0, '00', NULL, NULL, NULL),
            ('CN', 'es', 'China',                                                                       0, '00', NULL, NULL, NULL),
            ('CO', 'es', 'Colombia',                                                                    0, '00', NULL, NULL, NULL),
            ('CR', 'es', 'Costa Rica',                                                                  0, '00', 'Provincias', NULL, NULL),
            ('CS', 'es', 'Serbia y Montenegro',                                                         0, '00', NULL, NULL, NULL),
            ('CU', 'es', 'Cuba',                                                                        0, '00', NULL, NULL, NULL),
            ('CV', 'es', 'Cabo Verde',                                                                  0, '00', NULL, NULL, NULL),
            ('CX', 'es', 'Isla Christmas',                                                              0, '00', NULL, NULL, NULL),
            ('CY', 'es', 'Chipre',                                                                      0, '00', NULL, NULL, NULL),
            ('CZ', 'es', 'República Checa',                                                             0, '00', NULL, NULL, NULL),
            ('DE', 'es', 'Alemania',                                                                    0, '00', NULL, NULL, NULL),
            ('DJ', 'es', 'Yibuti',                                                                      0, '00', NULL, NULL, NULL),
            ('DK', 'es', 'Dinamarca',                                                                   0, '00', NULL, NULL, NULL),
            ('DM', 'es', 'Dominica',                                                                    0, '00', NULL, NULL, NULL),
            ('DO', 'es', 'República Dominicana',                                                        0, '00', NULL, NULL, NULL),
            ('DZ', 'es', 'Argelia',                                                                     0, '00', NULL, NULL, NULL),
            ('EC', 'es', 'Ecuador',                                                                     0, '00', NULL, NULL, NULL),
            ('EE', 'es', 'Estonia',                                                                     0, '00', NULL, NULL, NULL),
            ('EG', 'es', 'Egipto',                                                                      0, '00', NULL, NULL, NULL),
            ('EH', 'es', 'Sáhara Occidental',                                                           0, '00', NULL, NULL, NULL),
            ('ER', 'es', 'Eritrea',                                                                     0, '00', NULL, NULL, NULL),
            ('ES', 'es', 'España',                                                                      0, '34', 'Región', 'Provincia', NULL),
            ('ET', 'es', 'Etiopía',                                                                     0, '00', NULL, NULL, NULL),
            ('FI', 'es', 'Finlandia',                                                                   0, '00', NULL, NULL, NULL),
            ('FJ', 'es', 'Fiyi',                                                                        0, '00', NULL, NULL, NULL),
            ('FK', 'es', 'Islas Malvinas',                                                              0, '00', NULL, NULL, NULL),
            ('FM', 'es', 'Micronesia',                                                                  0, '00', NULL, NULL, NULL),
            ('FO', 'es', 'Islas Feroe',                                                                 0, '00', NULL, NULL, NULL),
            ('FR', 'es', 'Francia',                                                                     0, '33', NULL, NULL, NULL),
            ('GA', 'es', 'Gabón',                                                                       0, '00', NULL, NULL, NULL),
            ('GB', 'es', 'Reino Unido',                                                                 0, '44', NULL, NULL, NULL),
            ('GD', 'es', 'Granada',                                                                     0, '00', NULL, NULL, NULL),
            ('GE', 'es', 'Georgia',                                                                     0, '00', NULL, NULL, NULL),
            ('GF', 'es', 'Guayana Francesa',                                                            0, '00', NULL, NULL, NULL),
            ('GG', 'es', 'Guernsey',                                                                    0, '00', NULL, NULL, NULL),
            ('GH', 'es', 'Ghana',                                                                       0, '00', NULL, NULL, NULL),
            ('GI', 'es', 'Gibraltar',                                                                   0, '00', NULL, NULL, NULL),
            ('GL', 'es', 'Groenlandia',                                                                 0, '00', NULL, NULL, NULL),
            ('GM', 'es', 'Gambia',                                                                      0, '00', NULL, NULL, NULL),
            ('GN', 'es', 'Guinea',                                                                      0, '00', NULL, NULL, NULL),
            ('GP', 'es', 'Guadalupe',                                                                   0, '00', NULL, NULL, NULL),
            ('GQ', 'es', 'Guinea Ecuatorial',                                                           0, '00', NULL, NULL, NULL),
            ('GR', 'es', 'Grecia',                                                                      0, '00', NULL, NULL, NULL),
            ('GS', 'es', 'Islas Georgia del Sur y Sandwich del Sur',                                    0, '00', NULL, NULL, NULL),
            ('GT', 'es', 'Guatemala',                                                                   0, '00', NULL, NULL, NULL),
            ('GU', 'es', 'Guam',                                                                        0, '00', NULL, NULL, NULL),
            ('GW', 'es', 'Guinea-Bissau',                                                               0, '00', NULL, NULL, NULL),
            ('GY', 'es', 'Guyana',                                                                      0, '00', NULL, NULL, NULL),
            ('HK', 'es', 'Región Administrativa Especial de Hong Kong de la República Popular China',   0, '00', NULL, NULL, NULL),
            ('HM', 'es', 'Islas Heard y McDonald',                                                      0, '00', NULL, NULL, NULL),
            ('HN', 'es', 'Honduras',                                                                    0, '00', NULL, NULL, NULL),
            ('HR', 'es', 'Croacia',                                                                     0, '00', NULL, NULL, NULL),
            ('HT', 'es', 'Haití',                                                                       0, '00', NULL, NULL, NULL),
            ('HU', 'es', 'Hungría',                                                                     0, '00', NULL, NULL, NULL),
            ('ID', 'es', 'Indonesia',                                                                   0, '00', NULL, NULL, NULL),
            ('IE', 'es', 'Irlanda',                                                                     0, '00', NULL, NULL, NULL),
            ('IL', 'es', 'Israel',                                                                      0, '00', NULL, NULL, NULL),
            ('IM', 'es', 'Isla de Man',                                                                 0, '00', NULL, NULL, NULL),
            ('IN', 'es', 'India', 0, '00', NULL, NULL, NULL),
            ('IO', 'es', 'Territorio Británico del Océano Índico', 0, '00', NULL, NULL, NULL),
            ('IQ', 'es', 'Iraq', 0, '00', NULL, NULL, NULL),
            ('IR', 'es', 'Irán', 0, '00', NULL, NULL, NULL),
            ('IS', 'es', 'Islandia', 0, '00', NULL, NULL, NULL),
            ('IT', 'es', 'Italia', 0, '00', NULL, NULL, NULL),
            ('JE', 'es', 'Jersey', 0, '00', NULL, NULL, NULL),
            ('JM', 'es', 'Jamaica', 0, '00', NULL, NULL, NULL),
            ('JO', 'es', 'Jordania', 0, '00', NULL, NULL, NULL),
            ('JP', 'es', 'Japón', 0, '00', NULL, NULL, NULL),
            ('KE', 'es', 'Kenia', 0, '00', NULL, NULL, NULL),
            ('KG', 'es', 'Kirguistán', 0, '00', NULL, NULL, NULL),
            ('KH', 'es', 'Camboya', 0, '00', NULL, NULL, NULL),
            ('KI', 'es', 'Kiribati', 0, '00', NULL, NULL, NULL),
            ('KM', 'es', 'Comoras', 0, '00', NULL, NULL, NULL),
            ('KN', 'es', 'San Cristóbal y Nieves', 0, '00', NULL, NULL, NULL),
            ('KP', 'es', 'Corea del Norte', 0, '00', NULL, NULL, NULL),
            ('KR', 'es', 'Corea del Sur', 0, '00', NULL, NULL, NULL),
            ('KW', 'es', 'Kuwait', 0, '00', NULL, NULL, NULL),
            ('KY', 'es', 'Islas Caimán', 0, '00', NULL, NULL, NULL),
            ('KZ', 'es', 'Kazajistán', 0, '00', NULL, NULL, NULL),
            ('LA', 'es', 'Laos', 0, '00', NULL, NULL, NULL),
            ('LB', 'es', 'Líbano', 0, '00', NULL, NULL, NULL),
            ('LC', 'es', 'Santa Lucía', 0, '00', NULL, NULL, NULL),
            ('LI', 'es', 'Liechtenstein', 0, '00', NULL, NULL, NULL),
            ('LK', 'es', 'Sri Lanka', 0, '00', NULL, NULL, NULL),
            ('LR', 'es', 'Liberia', 0, '00', NULL, NULL, NULL),
            ('LS', 'es', 'Lesoto', 0, '00', NULL, NULL, NULL),
            ('LT', 'es', 'Lituania', 0, '00', NULL, NULL, NULL),
            ('LU', 'es', 'Luxemburgo', 0, '00', NULL, NULL, NULL),
            ('LV', 'es', 'Letonia', 0, '00', NULL, NULL, NULL),
            ('LY', 'es', 'Libia', 0, '00', NULL, NULL, NULL),
            ('MA', 'es', 'Marruecos', 0, '00', NULL, NULL, NULL),
            ('MC', 'es', 'Mónaco', 0, '00', NULL, NULL, NULL),
            ('MD', 'es', 'Moldavia', 0, '00', NULL, NULL, NULL),
            ('ME', 'es', 'Montenegro', 0, '00', NULL, NULL, NULL),
            ('MF', 'es', 'San Martín', 0, '00', NULL, NULL, NULL),
            ('MG', 'es', 'Madagascar', 0, '00', NULL, NULL, NULL),
            ('MH', 'es', 'Islas Marshall', 0, '00', NULL, NULL, NULL),
            ('MK', 'es', 'Macedonia', 0, '00', NULL, NULL, NULL),
            ('ML', 'es', 'Mali', 0, '00', NULL, NULL, NULL),
            ('MM', 'es', 'Myanmar', 0, '00', NULL, NULL, NULL),
            ('MN', 'es', 'Mongolia', 0, '00', NULL, NULL, NULL),
            ('MO', 'es', 'Región Administrativa Especial de Macao de la República Popular China',   0, '00', NULL, NULL, NULL),
            ('MP', 'es', 'Islas Marianas del Norte', 0, '00', NULL, NULL, NULL),
            ('MQ', 'es', 'Martinica', 0, '00', NULL, NULL, NULL),
            ('MR', 'es', 'Mauritania', 0, '00', NULL, NULL, NULL),
            ('MS', 'es', 'Montserrat', 0, '00', NULL, NULL, NULL),
            ('MT', 'es', 'Malta', 0, '00', NULL, NULL, NULL),
            ('MU', 'es', 'Mauricio', 0, '00', NULL, NULL, NULL),
            ('MV', 'es', 'Maldivas', 0, '00', NULL, NULL, NULL),
            ('MW', 'es', 'Malaui', 0, '00', NULL, NULL, NULL),
            ('MX', 'es', 'México', 0, '00', 'Estados', NULL, NULL),
            ('MY', 'es', 'Malasia', 0, '00', NULL, NULL, NULL),
            ('MZ', 'es', 'Mozambique', 0, '00', NULL, NULL, NULL),
            ('NA', 'es', 'Namibia', 0, '00', NULL, NULL, NULL),
            ('NC', 'es', 'Nueva Caledonia', 0, '00', NULL, NULL, NULL),
            ('NE', 'es', 'Níger', 0, '00', NULL, NULL, NULL),
            ('NF', 'es', 'Isla Norfolk', 0, '00', NULL, NULL, NULL),
            ('NG', 'es', 'Nigeria', 0, '00', NULL, NULL, NULL),
            ('NI', 'es', 'Nicaragua', 0, '00', NULL, NULL, NULL),
            ('NL', 'es', 'Países Bajos', 0, '00', NULL, NULL, NULL),
            ('NO', 'es', 'Noruega', 0, '00', NULL, NULL, NULL),
            ('NP', 'es', 'Nepal', 0, '00', NULL, NULL, NULL),
            ('NR', 'es', 'Nauru', 0, '00', NULL, NULL, NULL),
            ('NU', 'es', 'Isla Niue', 0, '00', NULL, NULL, NULL),
            ('NZ', 'es', 'Nueva Zelanda', 0, '00', NULL, NULL, NULL),
            ('OM', 'es', 'Omán', 0, '00', NULL, NULL, NULL),
            ('PA', 'es', 'Panamá', 0, '507', NULL, NULL, NULL),
            ('PE', 'es', 'Perú', 0, '00', NULL, NULL, NULL),
            ('PF', 'es', 'Polinesia Francesa', 0, '00', NULL, NULL, NULL),
            ('PG', 'es', 'Papúa Nueva Guinea', 0, '00', NULL, NULL, NULL),
            ('PH', 'es', 'Filipinas', 0, '00', NULL, NULL, NULL),
            ('PK', 'es', 'Pakistán', 0, '00', NULL, NULL, NULL),
            ('PL', 'es', 'Polonia', 0, '00', NULL, NULL, NULL),
            ('PM', 'es', 'San Pedro y Miquelón', 0, '00', NULL, NULL, NULL),
            ('PN', 'es', 'Pitcairn', 0, '00', NULL, NULL, NULL),
            ('PR', 'es', 'Puerto Rico', 0, '00', NULL, NULL, NULL),
            ('PS', 'es', 'Palestina', 0, '00', NULL, NULL, NULL),
            ('PT', 'es', 'Portugal', 0, '00', NULL, NULL, NULL),
            ('PW', 'es', 'Palau', 0, '00', NULL, NULL, NULL),
            ('PY', 'es', 'Paraguay', 0, '00', NULL, NULL, NULL),
            ('QA', 'es', 'Qatar', 0, '00', NULL, NULL, NULL),
            ('RE', 'es', 'Reunión', 0, '00', NULL, NULL, NULL),
            ('RO', 'es', 'Rumanía', 0, '00', NULL, NULL, NULL),
            ('RS', 'es', 'Serbia', 0, '00', NULL, NULL, NULL),
            ('RU', 'es', 'Rusia', 0, '00', NULL, NULL, NULL),
            ('RW', 'es', 'Ruanda', 0, '00', NULL, NULL, NULL),
            ('SA', 'es', 'Arabia Saudí', 0, '00', NULL, NULL, NULL),
            ('SB', 'es', 'Islas Salomón', 0, '00', NULL, NULL, NULL),
            ('SC', 'es', 'Seychelles', 0, '00', NULL, NULL, NULL),
            ('SD', 'es', 'Sudán', 0, '00', NULL, NULL, NULL),
            ('SE', 'es', 'Suecia', 0, '00', NULL, NULL, NULL),
            ('SG', 'es', 'Singapur', 0, '00', NULL, NULL, NULL),
            ('SH', 'es', 'Santa Elena', 0, '00', NULL, NULL, NULL),
            ('SI', 'es', 'Eslovenia', 0, '00', NULL, NULL, NULL),
            ('SJ', 'es', 'Svalbard y Jan Mayen', 0, '00', NULL, NULL, NULL),
            ('SK', 'es', 'Eslovaquia', 0, '00', NULL, NULL, NULL),
            ('SL', 'es', 'Sierra Leona', 0, '00', NULL, NULL, NULL),
            ('SM', 'es', 'San Marino', 0, '00', NULL, NULL, NULL),
            ('SN', 'es', 'Senegal', 0, '00', NULL, NULL, NULL),
            ('SO', 'es', 'Somalia', 0, '00', NULL, NULL, NULL),
            ('SR', 'es', 'Surinam', 0, '00', NULL, NULL, NULL),
            ('ST', 'es', 'Santo Tomé y Príncipe', 0, '00', NULL, NULL, NULL),
            ('SV', 'es', 'El Salvador', 0, '00', NULL, NULL, NULL),
            ('SY', 'es', 'Siria', 0, '00', NULL, NULL, NULL),
            ('SZ', 'es', 'Suazilandia', 0, '00', NULL, NULL, NULL),
            ('TC', 'es', 'Islas Turcas y Caicos', 0, '00', NULL, NULL, NULL),
            ('TD', 'es', 'Chad', 0, '00', NULL, NULL, NULL),
            ('TF', 'es', 'Territorios Australes Franceses', 0, '00', NULL, NULL, NULL),
            ('TG', 'es', 'Togo', 0, '00', NULL, NULL, NULL),
            ('TH', 'es', 'Tailandia', 0, '00', NULL, NULL, NULL),
            ('TJ', 'es', 'Tayikistán', 0, '00', NULL, NULL, NULL),
            ('TK', 'es', 'Tokelau', 0, '00', NULL, NULL, NULL),
            ('TL', 'es', 'Timor Oriental', 0, '00', NULL, NULL, NULL),
            ('TM', 'es', 'Turkmenistán', 0, '00', NULL, NULL, NULL),
            ('TN', 'es', 'Túnez', 0, '00', NULL, NULL, NULL),
            ('TO', 'es', 'Tonga', 0, '00', NULL, NULL, NULL),
            ('TR', 'es', 'Turquía', 0, '00', NULL, NULL, NULL),
            ('TT', 'es', 'Trinidad y Tobago', 0, '00', NULL, NULL, NULL),
            ('TV', 'es', 'Tuvalu', 0, '00', NULL, NULL, NULL),
            ('TW', 'es', 'Taiwán', 0, '00', NULL, NULL, NULL),
            ('TZ', 'es', 'Tanzania', 0, '00', NULL, NULL, NULL),
            ('UA', 'es', 'Ucrania', 0, '00', NULL, NULL, NULL),
            ('UG', 'es', 'Uganda', 0, '00', NULL, NULL, NULL),
            ('UM', 'es', 'Islas menores alejadas de los Estados Unidos', 0, '00', NULL, NULL, NULL),
            ('US', 'es', 'Estados Unidos', 0, '00', NULL, NULL, NULL),
            ('UY', 'es', 'Uruguay', 0, '00', NULL, NULL, NULL),
            ('UZ', 'es', 'Uzbekistán', 0, '00', NULL, NULL, NULL),
            ('VA', 'es', 'Ciudad del Vaticano', 0, '00', NULL, NULL, NULL),
            ('VC', 'es', 'San Vicente y las Granadinas', 0, '00', NULL, NULL, NULL),
            ('VE', 'es', 'Venezuela', 0, '00', NULL, NULL, NULL),
            ('VG', 'es', 'Islas Vírgenes Británicas', 0, '00', NULL, NULL, NULL),
            ('VI', 'es', 'Islas Vírgenes de los Estados Unidos', 0, '00', NULL, NULL, NULL),
            ('VN', 'es', 'Vietnam', 0, '00', NULL, NULL, NULL),
            ('VU', 'es', 'Vanuatu', 0, '00', NULL, NULL, NULL),
            ('WF', 'es', 'Wallis y Futuna', 0, '00', NULL, NULL, NULL),
            ('WS', 'es', 'Samoa', 0, '00', NULL, NULL, NULL),
            ('YE', 'es', 'Yemen', 0, '00', NULL, NULL, NULL),
            ('YT', 'es', 'Mayotte', 0, '00', NULL, NULL, NULL),
            ('ZA', 'es', 'Sudáfrica', 0, '00', NULL, NULL, NULL),
            ('ZM', 'es', 'Zambia', 0, '00', NULL, NULL, NULL),
            ('ZW', 'es', 'Zimbabue', 0, '00', NULL, NULL, NULL),
            ('ZZ', 'es', 'Región desconocida o no válida', 0, '00', NULL, NULL, NULL);"));
            
            //DATOS 001_002_country (en)
            DB::insert(DB::raw("INSERT INTO `001_002_country` (`id_002`, `lang_002`, `name_002`, `sorting_002`, `prefix_002`, `territorial_area_1_002`, `territorial_area_2_002`, `territorial_area_3_002`) VALUES
            ('AD', 'en', 'Andorra', 0, '00', NULL, NULL, NULL),
            ('AE', 'en', 'United Arab Emirates', 0, '00', NULL, NULL, NULL),
            ('AF', 'en', 'Afghanistan', 0, '00', NULL, NULL, NULL),
            ('AG', 'en', 'Antigua and Barbuda', 0, '00', NULL, NULL, NULL),
            ('AI', 'en', 'Anguilla', 0, '00', NULL, NULL, NULL),
            ('AL', 'en', 'Albania', 0, '00', NULL, NULL, NULL),
            ('AM', 'en', 'Armenia', 0, '00', NULL, NULL, NULL),
            ('AN', 'en', 'Netherlands Antilles', 0, '00', NULL, NULL, NULL),
            ('AO', 'en', 'Angola', 0, '00', NULL, NULL, NULL),
            ('AQ', 'en', 'Antarctica', 0, '00', NULL, NULL, NULL),
            ('AR', 'en', 'Argentina', 0, '00', NULL, NULL, NULL),
            ('AS', 'en', 'American Samoa', 0, '00', NULL, NULL, NULL),
            ('AT', 'en', 'Austria', 0, '00', NULL, NULL, NULL),
            ('AU', 'en', 'Australia', 0, '00', NULL, NULL, NULL),
            ('AW', 'en', 'Aruba', 0, '00', NULL, NULL, NULL),
            ('AX', 'en', 'Åland Islands', 0, '00', NULL, NULL, NULL),
            ('AZ', 'en', 'Azerbaijan', 0, '00', NULL, NULL, NULL),
            ('BA', 'en', 'Bosnia and Herzegovina', 0, '00', NULL, NULL, NULL),
            ('BB', 'en', 'Barbados', 0, '00', NULL, NULL, NULL),
            ('BD', 'en', 'Bangladesh', 0, '00', NULL, NULL, NULL),
            ('BE', 'en', 'Belgium', 0, '00', NULL, NULL, NULL),
            ('BF', 'en', 'Burkina Faso', 0, '00', NULL, NULL, NULL),
            ('BG', 'en', 'Bulgaria', 0, '00', NULL, NULL, NULL),
            ('BH', 'en', 'Bahrain', 0, '00', NULL, NULL, NULL),
            ('BI', 'en', 'Burundi', 0, '00', NULL, NULL, NULL),
            ('BJ', 'en', 'Benin', 0, '00', NULL, NULL, NULL),
            ('BL', 'en', 'Saint Barthélemy', 0, '00', NULL, NULL, NULL),
            ('BM', 'en', 'Bermuda', 0, '00', NULL, NULL, NULL),
            ('BN', 'en', 'Brunei', 0, '00', NULL, NULL, NULL),
            ('BO', 'en', 'Bolivia', 0, '00', NULL, NULL, NULL),
            ('BR', 'en', 'Brazil', 0, '00', NULL, NULL, NULL),
            ('BS', 'en', 'Bahamas', 0, '00', NULL, NULL, NULL),
            ('BT', 'en', 'Bhutan', 0, '00', NULL, NULL, NULL),
            ('BV', 'en', 'Bouvet Island', 0, '00', NULL, NULL, NULL),
            ('BW', 'en', 'Botswana', 0, '00', NULL, NULL, NULL),
            ('BY', 'en', 'Belarus', 0, '00', NULL, NULL, NULL),
            ('BZ', 'en', 'Belize', 0, '00', NULL, NULL, NULL),
            ('CA', 'en', 'Canada', 0, '00', 'Provinces', NULL, NULL),
            ('CC', 'en', 'Cocos [Keeling] Islands', 0, '00', NULL, NULL, NULL),
            ('CD', 'en', 'Congo - Kinshasa', 0, '00', NULL, NULL, NULL),
            ('CF', 'en', 'Central African Republic', 0, '00', NULL, NULL, NULL),
            ('CG', 'en', 'Congo - Brazzaville', 0, '00', NULL, NULL, NULL),
            ('CH', 'en', 'Switzerland', 0, '00', NULL, NULL, NULL),
            ('CI', 'en', 'Côte d’Ivoire', 0, '00', NULL, NULL, NULL),
            ('CK', 'en', 'Cook Islands', 0, '00', NULL, NULL, NULL),
            ('CL', 'en', 'Chile', 0, '00', NULL, NULL, NULL),
            ('CM', 'en', 'Cameroon', 0, '00', NULL, NULL, NULL),
            ('CN', 'en', 'China', 0, '00', NULL, NULL, NULL),
            ('CO', 'en', 'Colombia', 0, '00', NULL, NULL, NULL),
            ('CR', 'en', 'Costa Rica', 0, '00', 'Provinces', NULL, NULL),
            ('CS', 'en', 'Serbia and Montenegro', 0, '00', NULL, NULL, NULL),
            ('CU', 'en', 'Cuba', 0, '00', NULL, NULL, NULL),
            ('CV', 'en', 'Cape Verde', 0, '00', NULL, NULL, NULL),
            ('CX', 'en', 'Christmas Island', 0, '00', NULL, NULL, NULL),
            ('CY', 'en', 'Cyprus', 0, '00', NULL, NULL, NULL),
            ('CZ', 'en', 'Czech Republic', 0, '00', NULL, NULL, NULL),
            ('DE', 'en', 'Germany', 0, '00', NULL, NULL, NULL),
            ('DJ', 'en', 'Djibouti', 0, '00', NULL, NULL, NULL),
            ('DK', 'en', 'Denmark', 0, '00', NULL, NULL, NULL),
            ('DM', 'en', 'Dominica', 0, '00', NULL, NULL, NULL),
            ('DO', 'en', 'Dominican Republic', 0, '00', NULL, NULL, NULL),
            ('DZ', 'en', 'Algeria', 0, '00', NULL, NULL, NULL),
            ('EC', 'en', 'Ecuador', 0, '00', NULL, NULL, NULL),
            ('EE', 'en', 'Estonia', 0, '00', NULL, NULL, NULL),
            ('EG', 'en', 'Egypt', 0, '00', NULL, NULL, NULL),
            ('EH', 'en', 'Western Sahara', 0, '00', NULL, NULL, NULL),
            ('ER', 'en', 'Eritrea', 0, '00', NULL, NULL, NULL),
            ('ES', 'en', 'Spain', 0, '34', 'Region', 'Province', NULL),
            ('ET', 'en', 'Ethiopia', 0, '00', NULL, NULL, NULL),
            ('FI', 'en', 'Finland', 0, '00', NULL, NULL, NULL),
            ('FJ', 'en', 'Fiji', 0, '00', NULL, NULL, NULL),
            ('FK', 'en', 'Falkland Islands', 0, '00', NULL, NULL, NULL),
            ('FM', 'en', 'Micronesia', 0, '00', NULL, NULL, NULL),
            ('FO', 'en', 'Faroe Islands', 0, '00', NULL, NULL, NULL),
            ('FR', 'en', 'France', 0, '33', NULL, NULL, NULL),
            ('GA', 'en', 'Gabon', 0, '00', NULL, NULL, NULL),
            ('GB', 'en', 'United Kingdom', 0, '44', NULL, NULL, NULL),
            ('GD', 'en', 'Grenada', 0, '00', NULL, NULL, NULL),
            ('GE', 'en', 'Georgia', 0, '00', NULL, NULL, NULL),
            ('GF', 'en', 'French Guiana', 0, '00', NULL, NULL, NULL),
            ('GG', 'en', 'Guernsey', 0, '00', NULL, NULL, NULL),
            ('GH', 'en', 'Ghana', 0, '00', NULL, NULL, NULL),
            ('GI', 'en', 'Gibraltar', 0, '00', NULL, NULL, NULL),
            ('GL', 'en', 'Greenland', 0, '00', NULL, NULL, NULL),
            ('GM', 'en', 'Gambia', 0, '00', NULL, NULL, NULL),
            ('GN', 'en', 'Guinea', 0, '00', NULL, NULL, NULL),
            ('GP', 'en', 'Guadeloupe', 0, '00', NULL, NULL, NULL),
            ('GQ', 'en', 'Equatorial Guinea', 0, '00', NULL, NULL, NULL),
            ('GR', 'en', 'Greece', 0, '00', NULL, NULL, NULL),
            ('GS', 'en', 'South Georgia and the South Sandwich Islands', 0, '00', NULL, NULL, NULL),
            ('GT', 'en', 'Guatemala', 0, '00', NULL, NULL, NULL),
            ('GU', 'en', 'Guam', 0, '00', NULL, NULL, NULL),
            ('GW', 'en', 'Guinea-Bissau', 0, '00', NULL, NULL, NULL),
            ('GY', 'en', 'Guyana', 0, '00', NULL, NULL, NULL),
            ('HK', 'en', 'Hong Kong SAR China', 0, '00', NULL, NULL, NULL),
            ('HM', 'en', 'Heard Island and McDonald Islands', 0, '00', NULL, NULL, NULL),
            ('HN', 'en', 'Honduras', 0, '00', NULL, NULL, NULL),
            ('HR', 'en', 'Croatia', 0, '00', NULL, NULL, NULL),
            ('HT', 'en', 'Haiti', 0, '00', NULL, NULL, NULL),
            ('HU', 'en', 'Hungary', 0, '00', NULL, NULL, NULL),
            ('ID', 'en', 'Indonesia', 0, '00', NULL, NULL, NULL),
            ('IE', 'en', 'Ireland', 0, '00', NULL, NULL, NULL),
            ('IL', 'en', 'Israel', 0, '00', NULL, NULL, NULL),
            ('IM', 'en', 'Isle of Man', 0, '00', NULL, NULL, NULL),
            ('IN', 'en', 'India', 0, '00', NULL, NULL, NULL),
            ('IO', 'en', 'British Indian Ocean Territory', 0, '00', NULL, NULL, NULL),
            ('IQ', 'en', 'Iraq', 0, '00', NULL, NULL, NULL),
            ('IR', 'en', 'Iran', 0, '00', NULL, NULL, NULL),
            ('IS', 'en', 'Iceland', 0, '00', NULL, NULL, NULL),
            ('IT', 'en', 'Italy', 0, '00', NULL, NULL, NULL),
            ('JE', 'en', 'Jersey', 0, '00', NULL, NULL, NULL),
            ('JM', 'en', 'Jamaica', 0, '00', NULL, NULL, NULL),
            ('JO', 'en', 'Jordan', 0, '00', NULL, NULL, NULL),
            ('JP', 'en', 'Japan', 0, '00', NULL, NULL, NULL),
            ('KE', 'en', 'Kenya', 0, '00', NULL, NULL, NULL),
            ('KG', 'en', 'Kyrgyzstan', 0, '00', NULL, NULL, NULL),
            ('KH', 'en', 'Cambodia', 0, '00', NULL, NULL, NULL),
            ('KI', 'en', 'Kiribati', 0, '00', NULL, NULL, NULL),
            ('KM', 'en', 'Comoros', 0, '00', NULL, NULL, NULL),
            ('KN', 'en', 'Saint Kitts and Nevis', 0, '00', NULL, NULL, NULL),
            ('KP', 'en', 'North Korea', 0, '00', NULL, NULL, NULL),
            ('KR', 'en', 'South Korea', 0, '00', NULL, NULL, NULL),
            ('KW', 'en', 'Kuwait', 0, '00', NULL, NULL, NULL),
            ('KY', 'en', 'Cayman Islands', 0, '00', NULL, NULL, NULL),
            ('KZ', 'en', 'Kazakhstan', 0, '00', NULL, NULL, NULL),
            ('LA', 'en', 'Laos', 0, '00', NULL, NULL, NULL),
            ('LB', 'en', 'Lebanon', 0, '00', NULL, NULL, NULL),
            ('LC', 'en', 'Saint Lucia', 0, '00', NULL, NULL, NULL),
            ('LI', 'en', 'Liechtenstein', 0, '00', NULL, NULL, NULL),
            ('LK', 'en', 'Sri Lanka', 0, '00', NULL, NULL, NULL),
            ('LR', 'en', 'Liberia', 0, '00', NULL, NULL, NULL),
            ('LS', 'en', 'Lesotho', 0, '00', NULL, NULL, NULL),
            ('LT', 'en', 'Lithuania', 0, '00', NULL, NULL, NULL),
            ('LU', 'en', 'Luxembourg', 0, '00', NULL, NULL, NULL),
            ('LV', 'en', 'Latvia', 0, '00', NULL, NULL, NULL),
            ('LY', 'en', 'Libya', 0, '00', NULL, NULL, NULL),
            ('MA', 'en', 'Morocco', 0, '00', NULL, NULL, NULL),
            ('MC', 'en', 'Monaco', 0, '00', NULL, NULL, NULL),
            ('MD', 'en', 'Moldova', 0, '00', NULL, NULL, NULL),
            ('ME', 'en', 'Montenegro', 0, '00', NULL, NULL, NULL),
            ('MF', 'en', 'Saint Martin', 0, '00', NULL, NULL, NULL),
            ('MG', 'en', 'Madagascar', 0, '00', NULL, NULL, NULL),
            ('MH', 'en', 'Marshall Islands', 0, '00', NULL, NULL, NULL),
            ('MK', 'en', 'Macedonia', 0, '00', NULL, NULL, NULL),
            ('ML', 'en', 'Mali', 0, '00', NULL, NULL, NULL),
            ('MM', 'en', 'Myanmar [Burma]', 0, '00', NULL, NULL, NULL),
            ('MN', 'en', 'Mongolia', 0, '00', NULL, NULL, NULL),
            ('MO', 'en', 'Macau SAR China', 0, '00', NULL, NULL, NULL),
            ('MP', 'en', 'Northern Mariana Islands', 0, '00', NULL, NULL, NULL),
            ('MQ', 'en', 'Martinique', 0, '00', NULL, NULL, NULL),
            ('MR', 'en', 'Mauritania', 0, '00', NULL, NULL, NULL),
            ('MS', 'en', 'Montserrat', 0, '00', NULL, NULL, NULL),
            ('MT', 'en', 'Malta', 0, '00', NULL, NULL, NULL),
            ('MU', 'en', 'Mauritius', 0, '00', NULL, NULL, NULL),
            ('MV', 'en', 'Maldives', 0, '00', NULL, NULL, NULL),
            ('MW', 'en', 'Malawi', 0, '00', NULL, NULL, NULL),
            ('MX', 'en', 'Mexico', 0, '00', NULL, NULL, NULL),
            ('MY', 'en', 'Malaysia', 0, '00', NULL, NULL, NULL),
            ('MZ', 'en', 'Mozambique', 0, '00', NULL, NULL, NULL),
            ('NA', 'en', 'Namibia', 0, '00', NULL, NULL, NULL),
            ('NC', 'en', 'New Caledonia', 0, '00', NULL, NULL, NULL),
            ('NE', 'en', 'Niger', 0, '00', NULL, NULL, NULL),
            ('NF', 'en', 'Norfolk Island', 0, '00', NULL, NULL, NULL),
            ('NG', 'en', 'Nigeria', 0, '00', NULL, NULL, NULL),
            ('NI', 'en', 'Nicaragua', 0, '00', NULL, NULL, NULL),
            ('NL', 'en', 'Netherlands', 0, '00', NULL, NULL, NULL),
            ('NO', 'en', 'Norway', 0, '00', NULL, NULL, NULL),
            ('NP', 'en', 'Nepal', 0, '00', NULL, NULL, NULL),
            ('NR', 'en', 'Nauru', 0, '00', NULL, NULL, NULL),
            ('NU', 'en', 'Niue', 0, '00', NULL, NULL, NULL),
            ('NZ', 'en', 'New Zealand', 0, '00', NULL, NULL, NULL),
            ('OM', 'en', 'Oman', 0, '00', NULL, NULL, NULL),
            ('PA', 'en', 'Panama', 0, '507', NULL, NULL, NULL),
            ('PE', 'en', 'Peru', 0, '00', NULL, NULL, NULL),
            ('PF', 'en', 'French Polynesia', 0, '00', NULL, NULL, NULL),
            ('PG', 'en', 'Papua New Guinea', 0, '00', NULL, NULL, NULL),
            ('PH', 'en', 'Philippines', 0, '00', NULL, NULL, NULL),
            ('PK', 'en', 'Pakistan', 0, '00', NULL, NULL, NULL),
            ('PL', 'en', 'Poland', 0, '00', NULL, NULL, NULL),
            ('PM', 'en', 'Saint Pierre and Miquelon', 0, '00', NULL, NULL, NULL),
            ('PN', 'en', 'Pitcairn Islands', 0, '00', NULL, NULL, NULL),
            ('PR', 'en', 'Puerto Rico', 0, '00', NULL, NULL, NULL),
            ('PS', 'en', 'Palestinian Territories', 0, '00', NULL, NULL, NULL),
            ('PT', 'en', 'Portugal', 0, '00', NULL, NULL, NULL),
            ('PW', 'en', 'Palau', 0, '00', NULL, NULL, NULL),
            ('PY', 'en', 'Paraguay', 0, '00', NULL, NULL, NULL),
            ('QA', 'en', 'Qatar', 0, '00', NULL, NULL, NULL),
            ('RE', 'en', 'Réunion', 0, '00', NULL, NULL, NULL),
            ('RO', 'en', 'Romania', 0, '00', NULL, NULL, NULL),
            ('RS', 'en', 'Serbia', 0, '00', NULL, NULL, NULL),
            ('RU', 'en', 'Russia', 0, '00', NULL, NULL, NULL),
            ('RW', 'en', 'Rwanda', 0, '00', NULL, NULL, NULL),
            ('SA', 'en', 'Saudi Arabia', 0, '00', NULL, NULL, NULL),
            ('SB', 'en', 'Solomon Islands', 0, '00', NULL, NULL, NULL),
            ('SC', 'en', 'Seychelles', 0, '00', NULL, NULL, NULL),
            ('SD', 'en', 'Sudan', 0, '00', NULL, NULL, NULL),
            ('SE', 'en', 'Sweden', 0, '00', NULL, NULL, NULL),
            ('SG', 'en', 'Singapore', 0, '00', NULL, NULL, NULL),
            ('SH', 'en', 'Saint Helena', 0, '00', NULL, NULL, NULL),
            ('SI', 'en', 'Slovenia', 0, '00', NULL, NULL, NULL),
            ('SJ', 'en', 'Svalbard and Jan Mayen', 0, '00', NULL, NULL, NULL),
            ('SK', 'en', 'Slovakia', 0, '00', NULL, NULL, NULL),
            ('SL', 'en', 'Sierra Leone', 0, '00', NULL, NULL, NULL),
            ('SM', 'en', 'San Marino', 0, '00', NULL, NULL, NULL),
            ('SN', 'en', 'Senegal', 0, '00', NULL, NULL, NULL),
            ('SO', 'en', 'Somalia', 0, '00', NULL, NULL, NULL),
            ('SR', 'en', 'Suriname', 0, '00', NULL, NULL, NULL),
            ('ST', 'en', 'São Tomé and Príncipe', 0, '00', NULL, NULL, NULL),
            ('SV', 'en', 'El Salvador', 0, '00', NULL, NULL, NULL),
            ('SY', 'en', 'Syria', 0, '00', NULL, NULL, NULL),
            ('SZ', 'en', 'Swaziland', 0, '00', NULL, NULL, NULL),
            ('TC', 'en', 'Turks and Caicos Islands', 0, '00', NULL, NULL, NULL),
            ('TD', 'en', 'Chad', 0, '00', NULL, NULL, NULL),
            ('TF', 'en', 'French Southern Territories', 0, '00', NULL, NULL, NULL),
            ('TG', 'en', 'Togo', 0, '00', NULL, NULL, NULL),
            ('TH', 'en', 'Thailand', 0, '00', NULL, NULL, NULL),
            ('TJ', 'en', 'Tajikistan', 0, '00', NULL, NULL, NULL),
            ('TK', 'en', 'Tokelau', 0, '00', NULL, NULL, NULL),
            ('TL', 'en', 'Timor-Leste', 0, '00', NULL, NULL, NULL),
            ('TM', 'en', 'Turkmenistan', 0, '00', NULL, NULL, NULL),
            ('TN', 'en', 'Tunisia', 0, '00', NULL, NULL, NULL),
            ('TO', 'en', 'Tonga', 0, '00', NULL, NULL, NULL),
            ('TR', 'en', 'Turkey', 0, '00', NULL, NULL, NULL),
            ('TT', 'en', 'Trinidad and Tobago', 0, '00', NULL, NULL, NULL),
            ('TV', 'en', 'Tuvalu', 0, '00', NULL, NULL, NULL),
            ('TW', 'en', 'Taiwan', 0, '00', NULL, NULL, NULL),
            ('TZ', 'en', 'Tanzania', 0, '00', NULL, NULL, NULL),
            ('UA', 'en', 'Ukraine', 0, '00', NULL, NULL, NULL),
            ('UG', 'en', 'Uganda', 0, '00', NULL, NULL, NULL),
            ('UM', 'en', 'U.S. Minor Outlying Islands', 0, '00', NULL, NULL, NULL),
            ('US', 'en', 'United States', 0, '00', NULL, NULL, NULL),
            ('UY', 'en', 'Uruguay', 0, '00', NULL, NULL, NULL),
            ('UZ', 'en', 'Uzbekistan', 0, '00', NULL, NULL, NULL),
            ('VA', 'en', 'Vatican City', 0, '00', NULL, NULL, NULL),
            ('VC', 'en', 'Saint Vincent and the Grenadines', 0, '00', NULL, NULL, NULL),
            ('VE', 'en', 'Venezuela', 0, '00', NULL, NULL, NULL),
            ('VG', 'en', 'British Virgin Islands', 0, '00', NULL, NULL, NULL),
            ('VI', 'en', 'U.S. Virgin Islands', 0, '00', NULL, NULL, NULL),
            ('VN', 'en', 'Vietnam', 0, '00', NULL, NULL, NULL),
            ('VU', 'en', 'Vanuatu', 0, '00', NULL, NULL, NULL),
            ('WF', 'en', 'Wallis and Futuna', 0, '00', NULL, NULL, NULL),
            ('WS', 'en', 'Samoa', 0, '00', NULL, NULL, NULL),
            ('YE', 'en', 'Yemen', 0, '00', NULL, NULL, NULL),
            ('YT', 'en', 'Mayotte', 0, '00', NULL, NULL, NULL),
            ('ZA', 'en', 'South Africa', 0, '00', NULL, NULL, NULL),
            ('ZM', 'en', 'Zambia', 0, '00', NULL, NULL, NULL),
            ('ZW', 'en', 'Zimbabwe', 0, '00', NULL, NULL, NULL),
            ('ZZ', 'en', 'Unknown or Invalid Region', 0, '00', NULL, NULL, NULL);"));
            
            //DATOS 001_002_country (fr)
            DB::insert(DB::raw("INSERT INTO `001_002_country` (`id_002`, `lang_002`, `name_002`, `sorting_002`, `prefix_002`, `territorial_area_1_002`, `territorial_area_2_002`, `territorial_area_3_002`) VALUES
            ('AD', 'fr', 'Andorre', 0, '00', NULL, NULL, NULL),
            ('AE', 'fr', 'Émirats arabes unis', 0, '00', NULL, NULL, NULL),
            ('AF', 'fr', 'Afghanistan', 0, '00', NULL, NULL, NULL),
            ('AG', 'fr', 'Antigua-et-Barbuda', 0, '00', NULL, NULL, NULL),
            ('AI', 'fr', 'Anguilla', 0, '00', NULL, NULL, NULL),
            ('AL', 'fr', 'Albanie', 0, '00', NULL, NULL, NULL),
            ('AM', 'fr', 'Arménie', 0, '00', NULL, NULL, NULL),
            ('AN', 'fr', 'Antilles néerlandaises', 0, '00', NULL, NULL, NULL),
            ('AO', 'fr', 'Angola', 0, '00', NULL, NULL, NULL),
            ('AQ', 'fr', 'Antarctique', 0, '00', NULL, NULL, NULL),
            ('AR', 'fr', 'Argentine', 0, '00', NULL, NULL, NULL),
            ('AS', 'fr', 'Samoa américaines', 0, '00', NULL, NULL, NULL),
            ('AT', 'fr', 'Autriche', 0, '00', NULL, NULL, NULL),
            ('AU', 'fr', 'Australie', 0, '00', NULL, NULL, NULL),
            ('AW', 'fr', 'Aruba', 0, '00', NULL, NULL, NULL),
            ('AX', 'fr', 'Îles Åland', 0, '00', NULL, NULL, NULL),
            ('AZ', 'fr', 'Azerbaïdjan', 0, '00', NULL, NULL, NULL),
            ('BA', 'fr', 'Bosnie-Herzégovine', 0, '00', NULL, NULL, NULL),
            ('BB', 'fr', 'Barbade', 0, '00', NULL, NULL, NULL),
            ('BD', 'fr', 'Bangladesh', 0, '00', NULL, NULL, NULL),
            ('BE', 'fr', 'Belgique', 0, '00', NULL, NULL, NULL),
            ('BF', 'fr', 'Burkina Faso', 0, '00', NULL, NULL, NULL),
            ('BG', 'fr', 'Bulgarie', 0, '00', NULL, NULL, NULL),
            ('BH', 'fr', 'Bahreïn', 0, '00', NULL, NULL, NULL),
            ('BI', 'fr', 'Burundi', 0, '00', NULL, NULL, NULL),
            ('BJ', 'fr', 'Bénin', 0, '00', NULL, NULL, NULL),
            ('BL', 'fr', 'Saint-Barthélémy', 0, '00', NULL, NULL, NULL),
            ('BM', 'fr', 'Bermudes', 0, '00', NULL, NULL, NULL),
            ('BN', 'fr', 'Brunéi Darussalam', 0, '00', NULL, NULL, NULL),
            ('BO', 'fr', 'Bolivie', 0, '00', NULL, NULL, NULL),
            ('BR', 'fr', 'Brésil', 0, '00', NULL, NULL, NULL),
            ('BS', 'fr', 'Bahamas', 0, '00', NULL, NULL, NULL),
            ('BT', 'fr', 'Bhoutan', 0, '00', NULL, NULL, NULL),
            ('BV', 'fr', 'Île Bouvet', 0, '00', NULL, NULL, NULL),
            ('BW', 'fr', 'Botswana', 0, '00', NULL, NULL, NULL),
            ('BY', 'fr', 'Bélarus', 0, '00', NULL, NULL, NULL),
            ('BZ', 'fr', 'Belize', 0, '00', NULL, NULL, NULL),
            ('CA', 'fr', 'Canada', 0, '00', NULL, NULL, NULL),
            ('CC', 'fr', 'Îles Cocos - Keeling', 0, '00', NULL, NULL, NULL),
            ('CD', 'fr', 'République démocratique du Congo', 0, '00', NULL, NULL, NULL),
            ('CF', 'fr', 'République centrafricaine', 0, '00', NULL, NULL, NULL),
            ('CG', 'fr', 'Congo', 0, '00', NULL, NULL, NULL),
            ('CH', 'fr', 'Suisse', 0, '00', NULL, NULL, NULL),
            ('CI', 'fr', 'Côte d’Ivoire', 0, '00', NULL, NULL, NULL),
            ('CK', 'fr', 'Îles Cook', 0, '00', NULL, NULL, NULL),
            ('CL', 'fr', 'Chili', 0, '00', NULL, NULL, NULL),
            ('CM', 'fr', 'Cameroun', 0, '00', NULL, NULL, NULL),
            ('CN', 'fr', 'Chine', 0, '00', NULL, NULL, NULL),
            ('CO', 'fr', 'Colombie', 0, '00', NULL, NULL, NULL),
            ('CR', 'fr', 'Costa Rica', 0, '00', 'Provinces', NULL, NULL),
            ('CS', 'fr', 'Serbie-et-Monténégro', 0, '00', NULL, NULL, NULL),
            ('CU', 'fr', 'Cuba', 0, '00', NULL, NULL, NULL),
            ('CV', 'fr', 'Cap-Vert', 0, '00', NULL, NULL, NULL),
            ('CX', 'fr', 'Île Christmas', 0, '00', NULL, NULL, NULL),
            ('CY', 'fr', 'Chypre', 0, '00', NULL, NULL, NULL),
            ('CZ', 'fr', 'République tchèque', 0, '00', NULL, NULL, NULL),
            ('DE', 'fr', 'Allemagne', 0, '00', NULL, NULL, NULL),
            ('DJ', 'fr', 'Djibouti', 0, '00', NULL, NULL, NULL),
            ('DK', 'fr', 'Danemark', 0, '00', NULL, NULL, NULL),
            ('DM', 'fr', 'Dominique', 0, '00', NULL, NULL, NULL),
            ('DO', 'fr', 'République dominicaine', 0, '00', NULL, NULL, NULL),
            ('DZ', 'fr', 'Algérie', 0, '00', NULL, NULL, NULL),
            ('EC', 'fr', 'Équateur', 0, '00', NULL, NULL, NULL),
            ('EE', 'fr', 'Estonie', 0, '00', NULL, NULL, NULL),
            ('EG', 'fr', 'Égypte', 0, '00', NULL, NULL, NULL),
            ('EH', 'fr', 'Sahara occidental', 0, '00', NULL, NULL, NULL),
            ('ER', 'fr', 'Érythrée', 0, '00', NULL, NULL, NULL),
            ('ES', 'fr', 'Espagne', 0, '34', 'Région', 'Province', NULL),
            ('ET', 'fr', 'Éthiopie', 0, '00', NULL, NULL, NULL),
            ('FI', 'fr', 'Finlande', 0, '00', NULL, NULL, NULL),
            ('FJ', 'fr', 'Fidji', 0, '00', NULL, NULL, NULL),
            ('FK', 'fr', 'Îles Malouines', 0, '00', NULL, NULL, NULL),
            ('FM', 'fr', 'États fédérés de Micronésie', 0, '00', NULL, NULL, NULL),
            ('FO', 'fr', 'Îles Féroé', 0, '00', NULL, NULL, NULL),
            ('FR', 'fr', 'France', 0, '33', NULL, NULL, NULL),
            ('GA', 'fr', 'Gabon', 0, '00', NULL, NULL, NULL),
            ('GB', 'fr', 'Royaume-Uni', 0, '44', NULL, NULL, NULL),
            ('GD', 'fr', 'Grenade', 0, '00', NULL, NULL, NULL),
            ('GE', 'fr', 'Géorgie', 0, '00', NULL, NULL, NULL),
            ('GF', 'fr', 'Guyane française', 0, '00', NULL, NULL, NULL),
            ('GG', 'fr', 'Guernesey', 0, '00', NULL, NULL, NULL),
            ('GH', 'fr', 'Ghana', 0, '00', NULL, NULL, NULL),
            ('GI', 'fr', 'Gibraltar', 0, '00', NULL, NULL, NULL),
            ('GL', 'fr', 'Groenland', 0, '00', NULL, NULL, NULL),
            ('GM', 'fr', 'Gambie', 0, '00', NULL, NULL, NULL),
            ('GN', 'fr', 'Guinée', 0, '00', NULL, NULL, NULL),
            ('GP', 'fr', 'Guadeloupe', 0, '00', NULL, NULL, NULL),
            ('GQ', 'fr', 'Guinée équatoriale', 0, '00', NULL, NULL, NULL),
            ('GR', 'fr', 'Grèce', 0, '00', NULL, NULL, NULL),
            ('GS', 'fr', 'Géorgie du Sud et les îles Sandwich du Sud', 0, '00', NULL, NULL, NULL),
            ('GT', 'fr', 'Guatemala', 0, '00', NULL, NULL, NULL),
            ('GU', 'fr', 'Guam', 0, '00', NULL, NULL, NULL),
            ('GW', 'fr', 'Guinée-Bissau', 0, '00', NULL, NULL, NULL),
            ('GY', 'fr', 'Guyana', 0, '00', NULL, NULL, NULL),
            ('HK', 'fr', 'R.A.S. chinoise de Hong Kong', 0, '00', NULL, NULL, NULL),
            ('HM', 'fr', 'Îles Heard et MacDonald', 0, '00', NULL, NULL, NULL),
            ('HN', 'fr', 'Honduras', 0, '00', NULL, NULL, NULL),
            ('HR', 'fr', 'Croatie', 0, '00', NULL, NULL, NULL),
            ('HT', 'fr', 'Haïti', 0, '00', NULL, NULL, NULL),
            ('HU', 'fr', 'Hongrie', 0, '00', NULL, NULL, NULL),
            ('ID', 'fr', 'Indonésie', 0, '00', NULL, NULL, NULL),
            ('IE', 'fr', 'Irlande', 0, '00', NULL, NULL, NULL),
            ('IL', 'fr', 'Israël', 0, '00', NULL, NULL, NULL),
            ('IM', 'fr', 'Île de Man', 0, '00', NULL, NULL, NULL),
            ('IN', 'fr', 'Inde', 0, '00', NULL, NULL, NULL),
            ('IO', 'fr', 'Territoire britannique de l''océan Indien', 0, '00', NULL, NULL, NULL),
            ('IQ', 'fr', 'Irak', 0, '00', NULL, NULL, NULL),
            ('IR', 'fr', 'Iran', 0, '00', NULL, NULL, NULL),
            ('IS', 'fr', 'Islande', 0, '00', NULL, NULL, NULL),
            ('IT', 'fr', 'Italie', 0, '00', NULL, NULL, NULL),
            ('JE', 'fr', 'Jersey', 0, '00', NULL, NULL, NULL),
            ('JM', 'fr', 'Jamaïque', 0, '00', NULL, NULL, NULL),
            ('JO', 'fr', 'Jordanie', 0, '00', NULL, NULL, NULL),
            ('JP', 'fr', 'Japon', 0, '00', NULL, NULL, NULL),
            ('KE', 'fr', 'Kenya', 0, '00', NULL, NULL, NULL),
            ('KG', 'fr', 'Kirghizistan', 0, '00', NULL, NULL, NULL),
            ('KH', 'fr', 'Cambodge', 0, '00', NULL, NULL, NULL),
            ('KI', 'fr', 'Kiribati', 0, '00', NULL, NULL, NULL),
            ('KM', 'fr', 'Comores', 0, '00', NULL, NULL, NULL),
            ('KN', 'fr', 'Saint-Kitts-et-Nevis', 0, '00', NULL, NULL, NULL),
            ('KP', 'fr', 'Corée du Nord', 0, '00', NULL, NULL, NULL),
            ('KR', 'fr', 'Corée du Sud', 0, '00', NULL, NULL, NULL),
            ('KW', 'fr', 'Koweït', 0, '00', NULL, NULL, NULL),
            ('KY', 'fr', 'Îles Caïmans', 0, '00', NULL, NULL, NULL),
            ('KZ', 'fr', 'Kazakhstan', 0, '00', NULL, NULL, NULL),
            ('LA', 'fr', 'Laos', 0, '00', NULL, NULL, NULL),
            ('LB', 'fr', 'Liban', 0, '00', NULL, NULL, NULL),
            ('LC', 'fr', 'Sainte-Lucie', 0, '00', NULL, NULL, NULL),
            ('LI', 'fr', 'Liechtenstein', 0, '00', NULL, NULL, NULL),
            ('LK', 'fr', 'Sri Lanka', 0, '00', NULL, NULL, NULL),
            ('LR', 'fr', 'Libéria', 0, '00', NULL, NULL, NULL),
            ('LS', 'fr', 'Lesotho', 0, '00', NULL, NULL, NULL),
            ('LT', 'fr', 'Lituanie', 0, '00', NULL, NULL, NULL),
            ('LU', 'fr', 'Luxembourg', 0, '00', NULL, NULL, NULL),
            ('LV', 'fr', 'Lettonie', 0, '00', NULL, NULL, NULL),
            ('LY', 'fr', 'Libye', 0, '00', NULL, NULL, NULL),
            ('MA', 'fr', 'Maroc', 0, '00', NULL, NULL, NULL),
            ('MC', 'fr', 'Monaco', 0, '00', NULL, NULL, NULL),
            ('MD', 'fr', 'Moldavie', 0, '00', NULL, NULL, NULL),
            ('ME', 'fr', 'Monténégro', 0, '00', NULL, NULL, NULL),
            ('MF', 'fr', 'Saint-Martin', 0, '00', NULL, NULL, NULL),
            ('MG', 'fr', 'Madagascar', 0, '00', NULL, NULL, NULL),
            ('MH', 'fr', 'Îles Marshall', 0, '00', NULL, NULL, NULL),
            ('MK', 'fr', 'Macédoine', 0, '00', NULL, NULL, NULL),
            ('ML', 'fr', 'Mali', 0, '00', NULL, NULL, NULL),
            ('MM', 'fr', 'Myanmar', 0, '00', NULL, NULL, NULL),
            ('MN', 'fr', 'Mongolie', 0, '00', NULL, NULL, NULL),
            ('MO', 'fr', 'R.A.S. chinoise de Macao', 0, '00', NULL, NULL, NULL),
            ('MP', 'fr', 'Îles Mariannes du Nord', 0, '00', NULL, NULL, NULL),
            ('MQ', 'fr', 'Martinique', 0, '00', NULL, NULL, NULL),
            ('MR', 'fr', 'Mauritanie', 0, '00', NULL, NULL, NULL),
            ('MS', 'fr', 'Montserrat', 0, '00', NULL, NULL, NULL),
            ('MT', 'fr', 'Malte', 0, '00', NULL, NULL, NULL),
            ('MU', 'fr', 'Maurice', 0, '00', NULL, NULL, NULL),
            ('MV', 'fr', 'Maldives', 0, '00', NULL, NULL, NULL),
            ('MW', 'fr', 'Malawi', 0, '00', NULL, NULL, NULL),
            ('MX', 'fr', 'Mexique', 0, '00', NULL, NULL, NULL),
            ('MY', 'fr', 'Malaisie', 0, '00', NULL, NULL, NULL),
            ('MZ', 'fr', 'Mozambique', 0, '00', NULL, NULL, NULL),
            ('NA', 'fr', 'Namibie', 0, '00', NULL, NULL, NULL),
            ('NC', 'fr', 'Nouvelle-Calédonie', 0, '00', NULL, NULL, NULL),
            ('NE', 'fr', 'Niger', 0, '00', NULL, NULL, NULL),
            ('NF', 'fr', 'Île Norfolk', 0, '00', NULL, NULL, NULL),
            ('NG', 'fr', 'Nigéria', 0, '00', NULL, NULL, NULL),
            ('NI', 'fr', 'Nicaragua', 0, '00', NULL, NULL, NULL),
            ('NL', 'fr', 'Pays-Bas', 0, '00', NULL, NULL, NULL),
            ('NO', 'fr', 'Norvège', 0, '00', NULL, NULL, NULL),
            ('NP', 'fr', 'Népal', 0, '00', NULL, NULL, NULL),
            ('NR', 'fr', 'Nauru', 0, '00', NULL, NULL, NULL),
            ('NU', 'fr', 'Niue', 0, '00', NULL, NULL, NULL),
            ('NZ', 'fr', 'Nouvelle-Zélande', 0, '00', NULL, NULL, NULL),
            ('OM', 'fr', 'Oman', 0, '00', NULL, NULL, NULL),
            ('PA', 'fr', 'Panama', 0, '507', NULL, NULL, NULL),
            ('PE', 'fr', 'Pérou', 0, '00', NULL, NULL, NULL),
            ('PF', 'fr', 'Polynésie française', 0, '00', NULL, NULL, NULL),
            ('PG', 'fr', 'Papouasie-Nouvelle-Guinée', 0, '00', NULL, NULL, NULL),
            ('PH', 'fr', 'Philippines', 0, '00', NULL, NULL, NULL),
            ('PK', 'fr', 'Pakistan', 0, '00', NULL, NULL, NULL),
            ('PL', 'fr', 'Pologne', 0, '00', NULL, NULL, NULL),
            ('PM', 'fr', 'Saint-Pierre-et-Miquelon', 0, '00', NULL, NULL, NULL),
            ('PN', 'fr', 'Pitcairn', 0, '00', NULL, NULL, NULL),
            ('PR', 'fr', 'Porto Rico', 0, '00', NULL, NULL, NULL),
            ('PS', 'fr', 'Territoire palestinien', 0, '00', NULL, NULL, NULL),
            ('PT', 'fr', 'Portugal', 0, '00', NULL, NULL, NULL),
            ('PW', 'fr', 'Palaos', 0, '00', NULL, NULL, NULL),
            ('PY', 'fr', 'Paraguay', 0, '00', NULL, NULL, NULL),
            ('QA', 'fr', 'Qatar', 0, '00', NULL, NULL, NULL),
            ('RE', 'fr', 'Réunion', 0, '00', NULL, NULL, NULL),
            ('RO', 'fr', 'Roumanie', 0, '00', NULL, NULL, NULL),
            ('RS', 'fr', 'Serbie', 0, '00', NULL, NULL, NULL),
            ('RU', 'fr', 'Russie', 0, '00', NULL, NULL, NULL),
            ('RW', 'fr', 'Rwanda', 0, '00', NULL, NULL, NULL),
            ('SA', 'fr', 'Arabie saoudite', 0, '00', NULL, NULL, NULL),
            ('SB', 'fr', 'Îles Salomon', 0, '00', NULL, NULL, NULL),
            ('SC', 'fr', 'Seychelles', 0, '00', NULL, NULL, NULL),
            ('SD', 'fr', 'Soudan', 0, '00', NULL, NULL, NULL),
            ('SE', 'fr', 'Suède', 0, '00', NULL, NULL, NULL),
            ('SG', 'fr', 'Singapour', 0, '00', NULL, NULL, NULL),
            ('SH', 'fr', 'Sainte-Hélène', 0, '00', NULL, NULL, NULL),
            ('SI', 'fr', 'Slovénie', 0, '00', NULL, NULL, NULL),
            ('SJ', 'fr', 'Svalbard et Île Jan Mayen', 0, '00', NULL, NULL, NULL),
            ('SK', 'fr', 'Slovaquie', 0, '00', NULL, NULL, NULL),
            ('SL', 'fr', 'Sierra Leone', 0, '00', NULL, NULL, NULL),
            ('SM', 'fr', 'Saint-Marin', 0, '00', NULL, NULL, NULL),
            ('SN', 'fr', 'Sénégal', 0, '00', NULL, NULL, NULL),
            ('SO', 'fr', 'Somalie', 0, '00', NULL, NULL, NULL),
            ('SR', 'fr', 'Suriname', 0, '00', NULL, NULL, NULL),
            ('ST', 'fr', 'Sao Tomé-et-Principe', 0, '00', NULL, NULL, NULL),
            ('SV', 'fr', 'El Salvador', 0, '00', NULL, NULL, NULL),
            ('SY', 'fr', 'Syrie', 0, '00', NULL, NULL, NULL),
            ('SZ', 'fr', 'Swaziland', 0, '00', NULL, NULL, NULL),
            ('TC', 'fr', 'Îles Turks et Caïques', 0, '00', NULL, NULL, NULL),
            ('TD', 'fr', 'Tchad', 0, '00', NULL, NULL, NULL),
            ('TF', 'fr', 'Terres australes françaises', 0, '00', NULL, NULL, NULL),
            ('TG', 'fr', 'Togo', 0, '00', NULL, NULL, NULL),
            ('TH', 'fr', 'Thaïlande', 0, '00', NULL, NULL, NULL),
            ('TJ', 'fr', 'Tadjikistan', 0, '00', NULL, NULL, NULL),
            ('TK', 'fr', 'Tokelau', 0, '00', NULL, NULL, NULL),
            ('TL', 'fr', 'Timor oriental', 0, '00', NULL, NULL, NULL),
            ('TM', 'fr', 'Turkménistan', 0, '00', NULL, NULL, NULL),
            ('TN', 'fr', 'Tunisie', 0, '00', NULL, NULL, NULL),
            ('TO', 'fr', 'Tonga', 0, '00', NULL, NULL, NULL),
            ('TR', 'fr', 'Turquie', 0, '00', NULL, NULL, NULL),
            ('TT', 'fr', 'Trinité-et-Tobago', 0, '00', NULL, NULL, NULL),
            ('TV', 'fr', 'Tuvalu', 0, '00', NULL, NULL, NULL),
            ('TW', 'fr', 'Taïwan', 0, '00', NULL, NULL, NULL),
            ('TZ', 'fr', 'Tanzanie', 0, '00', NULL, NULL, NULL),
            ('UA', 'fr', 'Ukraine', 0, '00', NULL, NULL, NULL),
            ('UG', 'fr', 'Ouganda', 0, '00', NULL, NULL, NULL),
            ('UM', 'fr', 'Îles Mineures Éloignées des États-Unis', 0, '00', NULL, NULL, NULL),
            ('US', 'fr', 'États-Unis', 0, '00', NULL, NULL, NULL),
            ('UY', 'fr', 'Uruguay', 0, '00', NULL, NULL, NULL),
            ('UZ', 'fr', 'Ouzbékistan', 0, '00', NULL, NULL, NULL),
            ('VA', 'fr', 'État de la Cité du Vatican', 0, '00', NULL, NULL, NULL),
            ('VC', 'fr', 'Saint-Vincent-et-les Grenadines', 0, '00', NULL, NULL, NULL),
            ('VE', 'fr', 'Venezuela', 0, '00', NULL, NULL, NULL),
            ('VG', 'fr', 'Îles Vierges britanniques', 0, '00', NULL, NULL, NULL),
            ('VI', 'fr', 'Îles Vierges des États-Unis', 0, '00', NULL, NULL, NULL),
            ('VN', 'fr', 'Viêt Nam', 0, '00', NULL, NULL, NULL),
            ('VU', 'fr', 'Vanuatu', 0, '00', NULL, NULL, NULL),
            ('WF', 'fr', 'Wallis-et-Futuna', 0, '00', NULL, NULL, NULL),
            ('WS', 'fr', 'Samoa', 0, '00', NULL, NULL, NULL),
            ('YE', 'fr', 'Yémen', 0, '00', NULL, NULL, NULL),
            ('YT', 'fr', 'Mayotte', 0, '00', NULL, NULL, NULL),
            ('ZA', 'fr', 'Afrique du Sud', 0, '00', NULL, NULL, NULL),
            ('ZM', 'fr', 'Zambie', 0, '00', NULL, NULL, NULL),
            ('ZW', 'fr', 'Zimbabwe', 0, '00', NULL, NULL, NULL),
            ('ZZ', 'fr', 'région indéterminée', 0, '00', NULL, NULL, NULL);"));
            
            //DATOS 001_002_country (de)
            DB::insert(DB::raw("INSERT INTO `001_002_country` (`id_002`, `lang_002`, `name_002`, `sorting_002`, `prefix_002`, `territorial_area_1_002`, `territorial_area_2_002`, `territorial_area_3_002`) VALUES
            ('AD', 'de', 'Andorra', 0, '00', NULL, NULL, NULL),
            ('AE', 'de', 'Vereinigte Arabische Emirate', 0, '00', NULL, NULL, NULL),
            ('AF', 'de', 'Afghanistan', 0, '00', NULL, NULL, NULL),
            ('AG', 'de', 'Antigua und Barbuda', 0, '00', NULL, NULL, NULL),
            ('AI', 'de', 'Anguilla', 0, '00', NULL, NULL, NULL),
            ('AL', 'de', 'Albanien', 0, '00', NULL, NULL, NULL),
            ('AM', 'de', 'Armenien', 0, '00', NULL, NULL, NULL),
            ('AN', 'de', 'Niederländische Antillen', 0, '00', NULL, NULL, NULL),
            ('AO', 'de', 'Angola', 0, '00', NULL, NULL, NULL),
            ('AQ', 'de', 'Antarktis', 0, '00', NULL, NULL, NULL),
            ('AR', 'de', 'Argentinien', 0, '00', NULL, NULL, NULL),
            ('AS', 'de', 'Amerikanisch-Samoa', 0, '00', NULL, NULL, NULL),
            ('AT', 'de', 'Österreich', 0, '00', NULL, NULL, NULL),
            ('AU', 'de', 'Australien', 0, '00', NULL, NULL, NULL),
            ('AW', 'de', 'Aruba', 0, '00', NULL, NULL, NULL),
            ('AX', 'de', 'Alandinseln', 0, '00', NULL, NULL, NULL),
            ('AZ', 'de', 'Aserbaidschan', 0, '00', NULL, NULL, NULL),
            ('BA', 'de', 'Bosnien und Herzegowina', 0, '00', NULL, NULL, NULL),
            ('BB', 'de', 'Barbados', 0, '00', NULL, NULL, NULL),
            ('BD', 'de', 'Bangladesch', 0, '00', NULL, NULL, NULL),
            ('BE', 'de', 'Belgien', 0, '00', NULL, NULL, NULL),
            ('BF', 'de', 'Burkina Faso', 0, '00', NULL, NULL, NULL),
            ('BG', 'de', 'Bulgarien', 0, '00', NULL, NULL, NULL),
            ('BH', 'de', 'Bahrain', 0, '00', NULL, NULL, NULL),
            ('BI', 'de', 'Burundi', 0, '00', NULL, NULL, NULL),
            ('BJ', 'de', 'Benin', 0, '00', NULL, NULL, NULL),
            ('BL', 'de', 'St. Barthélemy', 0, '00', NULL, NULL, NULL),
            ('BM', 'de', 'Bermuda', 0, '00', NULL, NULL, NULL),
            ('BN', 'de', 'Brunei Darussalam', 0, '00', NULL, NULL, NULL),
            ('BO', 'de', 'Bolivien', 0, '00', NULL, NULL, NULL),
            ('BR', 'de', 'Brasilien', 0, '00', NULL, NULL, NULL),
            ('BS', 'de', 'Bahamas', 0, '00', NULL, NULL, NULL),
            ('BT', 'de', 'Bhutan', 0, '00', NULL, NULL, NULL),
            ('BV', 'de', 'Bouvetinsel', 0, '00', NULL, NULL, NULL),
            ('BW', 'de', 'Botsuana', 0, '00', NULL, NULL, NULL),
            ('BY', 'de', 'Belarus', 0, '00', NULL, NULL, NULL),
            ('BZ', 'de', 'Belize', 0, '00', NULL, NULL, NULL),
            ('CA', 'de', 'Kanada', 0, '00', NULL, NULL, NULL),
            ('CC', 'de', 'Kokosinseln', 0, '00', NULL, NULL, NULL),
            ('CD', 'de', 'Demokratische Republik Kongo', 0, '00', NULL, NULL, NULL),
            ('CF', 'de', 'Zentralafrikanische Republik', 0, '00', NULL, NULL, NULL),
            ('CG', 'de', 'Kongo', 0, '00', NULL, NULL, NULL),
            ('CH', 'de', 'Schweiz', 0, '00', NULL, NULL, NULL),
            ('CI', 'de', 'Côte d’Ivoire', 0, '00', NULL, NULL, NULL),
            ('CK', 'de', 'Cookinseln', 0, '00', NULL, NULL, NULL),
            ('CL', 'de', 'Chile', 0, '00', NULL, NULL, NULL),
            ('CM', 'de', 'Kamerun', 0, '00', NULL, NULL, NULL),
            ('CN', 'de', 'China', 0, '00', NULL, NULL, NULL),
            ('CO', 'de', 'Kolumbien', 0, '00', NULL, NULL, NULL),
            ('CR', 'de', 'Costa Rica', 0, '00', 'Provinzen', NULL, NULL),
            ('CS', 'de', 'Serbien und Montenegro', 0, '00', NULL, NULL, NULL),
            ('CU', 'de', 'Kuba', 0, '00', NULL, NULL, NULL),
            ('CV', 'de', 'Kap Verde', 0, '00', NULL, NULL, NULL),
            ('CX', 'de', 'Weihnachtsinsel', 0, '00', NULL, NULL, NULL),
            ('CY', 'de', 'Zypern', 0, '00', NULL, NULL, NULL),
            ('CZ', 'de', 'Tschechische Republik', 0, '00', NULL, NULL, NULL),
            ('DE', 'de', 'Deutschland', 0, '00', NULL, NULL, NULL),
            ('DJ', 'de', 'Dschibuti', 0, '00', NULL, NULL, NULL),
            ('DK', 'de', 'Dänemark', 0, '00', NULL, NULL, NULL),
            ('DM', 'de', 'Dominica', 0, '00', NULL, NULL, NULL),
            ('DO', 'de', 'Dominikanische Republik', 0, '00', NULL, NULL, NULL),
            ('DZ', 'de', 'Algerien', 0, '00', NULL, NULL, NULL),
            ('EC', 'de', 'Ecuador', 0, '00', NULL, NULL, NULL),
            ('EE', 'de', 'Estland', 0, '00', NULL, NULL, NULL),
            ('EG', 'de', 'Ägypten', 0, '00', NULL, NULL, NULL),
            ('EH', 'de', 'Westsahara', 0, '00', NULL, NULL, NULL),
            ('ER', 'de', 'Eritrea', 0, '00', NULL, NULL, NULL),
            ('ES', 'de', 'Spanien', 0, '34', 'Region', 'Provinz', NULL),
            ('ET', 'de', 'Äthiopien', 0, '00', NULL, NULL, NULL),
            ('FI', 'de', 'Finnland', 0, '00', NULL, NULL, NULL),
            ('FJ', 'de', 'Fidschi', 0, '00', NULL, NULL, NULL),
            ('FK', 'de', 'Falklandinseln', 0, '00', NULL, NULL, NULL),
            ('FM', 'de', 'Mikronesien', 0, '00', NULL, NULL, NULL),
            ('FO', 'de', 'Färöer', 0, '00', NULL, NULL, NULL),
            ('FR', 'de', 'Frankreich', 0, '33', NULL, NULL, NULL),
            ('GA', 'de', 'Gabun', 0, '00', NULL, NULL, NULL),
            ('GB', 'de', 'Vereinigtes Königreich', 0, '44', NULL, NULL, NULL),
            ('GD', 'de', 'Grenada', 0, '00', NULL, NULL, NULL),
            ('GE', 'de', 'Georgien', 0, '00', NULL, NULL, NULL),
            ('GF', 'de', 'Französisch-Guayana', 0, '00', NULL, NULL, NULL),
            ('GG', 'de', 'Guernsey', 0, '00', NULL, NULL, NULL),
            ('GH', 'de', 'Ghana', 0, '00', NULL, NULL, NULL),
            ('GI', 'de', 'Gibraltar', 0, '00', NULL, NULL, NULL),
            ('GL', 'de', 'Grönland', 0, '00', NULL, NULL, NULL),
            ('GM', 'de', 'Gambia', 0, '00', NULL, NULL, NULL),
            ('GN', 'de', 'Guinea', 0, '00', NULL, NULL, NULL),
            ('GP', 'de', 'Guadeloupe', 0, '00', NULL, NULL, NULL),
            ('GQ', 'de', 'Äquatorialguinea', 0, '00', NULL, NULL, NULL),
            ('GR', 'de', 'Griechenland', 0, '00', NULL, NULL, NULL),
            ('GS', 'de', 'Südgeorgien und die Südlichen Sandwichinseln', 0, '00', NULL, NULL, NULL),
            ('GT', 'de', 'Guatemala', 0, '00', NULL, NULL, NULL),
            ('GU', 'de', 'Guam', 0, '00', NULL, NULL, NULL),
            ('GW', 'de', 'Guinea-Bissau', 0, '00', NULL, NULL, NULL),
            ('GY', 'de', 'Guyana', 0, '00', NULL, NULL, NULL),
            ('HK', 'de', 'Sonderverwaltungszone Hongkong', 0, '00', NULL, NULL, NULL),
            ('HM', 'de', 'Heard- und McDonald-Inseln', 0, '00', NULL, NULL, NULL),
            ('HN', 'de', 'Honduras', 0, '00', NULL, NULL, NULL),
            ('HR', 'de', 'Kroatien', 0, '00', NULL, NULL, NULL),
            ('HT', 'de', 'Haiti', 0, '00', NULL, NULL, NULL),
            ('HU', 'de', 'Ungarn', 0, '00', NULL, NULL, NULL),
            ('ID', 'de', 'Indonesien', 0, '00', NULL, NULL, NULL),
            ('IE', 'de', 'Irland', 0, '00', NULL, NULL, NULL),
            ('IL', 'de', 'Israel', 0, '00', NULL, NULL, NULL),
            ('IM', 'de', 'Isle of Man', 0, '00', NULL, NULL, NULL),
            ('IN', 'de', 'Indien', 0, '00', NULL, NULL, NULL),
            ('IO', 'de', 'Britisches Territorium im Indischen Ozean', 0, '00', NULL, NULL, NULL),
            ('IQ', 'de', 'Irak', 0, '00', NULL, NULL, NULL),
            ('IR', 'de', 'Iran', 0, '00', NULL, NULL, NULL),
            ('IS', 'de', 'Island', 0, '00', NULL, NULL, NULL),
            ('IT', 'de', 'Italien', 0, '00', NULL, NULL, NULL),
            ('JE', 'de', 'Jersey', 0, '00', NULL, NULL, NULL),
            ('JM', 'de', 'Jamaika', 0, '00', NULL, NULL, NULL),
            ('JO', 'de', 'Jordanien', 0, '00', NULL, NULL, NULL),
            ('JP', 'de', 'Japan', 0, '00', NULL, NULL, NULL),
            ('KE', 'de', 'Kenia', 0, '00', NULL, NULL, NULL),
            ('KG', 'de', 'Kirgisistan', 0, '00', NULL, NULL, NULL),
            ('KH', 'de', 'Kambodscha', 0, '00', NULL, NULL, NULL),
            ('KI', 'de', 'Kiribati', 0, '00', NULL, NULL, NULL),
            ('KM', 'de', 'Komoren', 0, '00', NULL, NULL, NULL),
            ('KN', 'de', 'St. Kitts und Nevis', 0, '00', NULL, NULL, NULL),
            ('KP', 'de', 'Demokratische Volksrepublik Korea', 0, '00', NULL, NULL, NULL),
            ('KR', 'de', 'Republik Korea', 0, '00', NULL, NULL, NULL),
            ('KW', 'de', 'Kuwait', 0, '00', NULL, NULL, NULL),
            ('KY', 'de', 'Kaimaninseln', 0, '00', NULL, NULL, NULL),
            ('KZ', 'de', 'Kasachstan', 0, '00', NULL, NULL, NULL),
            ('LA', 'de', 'Laos', 0, '00', NULL, NULL, NULL),
            ('LB', 'de', 'Libanon', 0, '00', NULL, NULL, NULL),
            ('LC', 'de', 'St. Lucia', 0, '00', NULL, NULL, NULL),
            ('LI', 'de', 'Liechtenstein', 0, '00', NULL, NULL, NULL),
            ('LK', 'de', 'Sri Lanka', 0, '00', NULL, NULL, NULL),
            ('LR', 'de', 'Liberia', 0, '00', NULL, NULL, NULL),
            ('LS', 'de', 'Lesotho', 0, '00', NULL, NULL, NULL),
            ('LT', 'de', 'Litauen', 0, '00', NULL, NULL, NULL),
            ('LU', 'de', 'Luxemburg', 0, '00', NULL, NULL, NULL),
            ('LV', 'de', 'Lettland', 0, '00', NULL, NULL, NULL),
            ('LY', 'de', 'Libyen', 0, '00', NULL, NULL, NULL),
            ('MA', 'de', 'Marokko', 0, '00', NULL, NULL, NULL),
            ('MC', 'de', 'Monaco', 0, '00', NULL, NULL, NULL),
            ('MD', 'de', 'Republik Moldau', 0, '00', NULL, NULL, NULL),
            ('ME', 'de', 'Montenegro', 0, '00', NULL, NULL, NULL),
            ('MF', 'de', 'St. Martin', 0, '00', NULL, NULL, NULL),
            ('MG', 'de', 'Madagaskar', 0, '00', NULL, NULL, NULL),
            ('MH', 'de', 'Marshallinseln', 0, '00', NULL, NULL, NULL),
            ('MK', 'de', 'Mazedonien', 0, '00', NULL, NULL, NULL),
            ('ML', 'de', 'Mali', 0, '00', NULL, NULL, NULL),
            ('MM', 'de', 'Myanmar', 0, '00', NULL, NULL, NULL),
            ('MN', 'de', 'Mongolei', 0, '00', NULL, NULL, NULL),
            ('MO', 'de', 'Sonderverwaltungszone Macao', 0, '00', NULL, NULL, NULL),
            ('MP', 'de', 'Nördliche Marianen', 0, '00', NULL, NULL, NULL),
            ('MQ', 'de', 'Martinique', 0, '00', NULL, NULL, NULL),
            ('MR', 'de', 'Mauretanien', 0, '00', NULL, NULL, NULL),
            ('MS', 'de', 'Montserrat', 0, '00', NULL, NULL, NULL),
            ('MT', 'de', 'Malta', 0, '00', NULL, NULL, NULL),
            ('MU', 'de', 'Mauritius', 0, '00', NULL, NULL, NULL),
            ('MV', 'de', 'Malediven', 0, '00', NULL, NULL, NULL),
            ('MW', 'de', 'Malawi', 0, '00', NULL, NULL, NULL),
            ('MX', 'de', 'Mexiko', 0, '00', NULL, NULL, NULL),
            ('MY', 'de', 'Malaysia', 0, '00', NULL, NULL, NULL),
            ('MZ', 'de', 'Mosambik', 0, '00', NULL, NULL, NULL),
            ('NA', 'de', 'Namibia', 0, '00', NULL, NULL, NULL),
            ('NC', 'de', 'Neukaledonien', 0, '00', NULL, NULL, NULL),
            ('NE', 'de', 'Niger', 0, '00', NULL, NULL, NULL),
            ('NF', 'de', 'Norfolkinsel', 0, '00', NULL, NULL, NULL),
            ('NG', 'de', 'Nigeria', 0, '00', NULL, NULL, NULL),
            ('NI', 'de', 'Nicaragua', 0, '00', NULL, NULL, NULL),
            ('NL', 'de', 'Niederlande', 0, '00', NULL, NULL, NULL),
            ('NO', 'de', 'Norwegen', 0, '00', NULL, NULL, NULL),
            ('NP', 'de', 'Nepal', 0, '00', NULL, NULL, NULL),
            ('NR', 'de', 'Nauru', 0, '00', NULL, NULL, NULL),
            ('NU', 'de', 'Niue', 0, '00', NULL, NULL, NULL),
            ('NZ', 'de', 'Neuseeland', 0, '00', NULL, NULL, NULL),
            ('OM', 'de', 'Oman', 0, '00', NULL, NULL, NULL),
            ('PA', 'de', 'Panama', 0, '507', NULL, NULL, NULL),
            ('PE', 'de', 'Peru', 0, '00', NULL, NULL, NULL),
            ('PF', 'de', 'Französisch-Polynesien', 0, '00', NULL, NULL, NULL),
            ('PG', 'de', 'Papua-Neuguinea', 0, '00', NULL, NULL, NULL),
            ('PH', 'de', 'Philippinen', 0, '00', NULL, NULL, NULL),
            ('PK', 'de', 'Pakistan', 0, '00', NULL, NULL, NULL),
            ('PL', 'de', 'Polen', 0, '00', NULL, NULL, NULL),
            ('PM', 'de', 'St. Pierre und Miquelon', 0, '00', NULL, NULL, NULL),
            ('PN', 'de', 'Pitcairn', 0, '00', NULL, NULL, NULL),
            ('PR', 'de', 'Puerto Rico', 0, '00', NULL, NULL, NULL),
            ('PS', 'de', 'Palästinensische Gebiete', 0, '00', NULL, NULL, NULL),
            ('PT', 'de', 'Portugal', 0, '00', NULL, NULL, NULL),
            ('PW', 'de', 'Palau', 0, '00', NULL, NULL, NULL),
            ('PY', 'de', 'Paraguay', 0, '00', NULL, NULL, NULL),
            ('QA', 'de', 'Katar', 0, '00', NULL, NULL, NULL),
            ('RE', 'de', 'Réunion', 0, '00', NULL, NULL, NULL),
            ('RO', 'de', 'Rumänien', 0, '00', NULL, NULL, NULL),
            ('RS', 'de', 'Serbien', 0, '00', NULL, NULL, NULL),
            ('RU', 'de', 'Russische Föderation', 0, '00', NULL, NULL, NULL),
            ('RW', 'de', 'Ruanda', 0, '00', NULL, NULL, NULL),
            ('SA', 'de', 'Saudi-Arabien', 0, '00', NULL, NULL, NULL),
            ('SB', 'de', 'Salomonen', 0, '00', NULL, NULL, NULL),
            ('SC', 'de', 'Seychellen', 0, '00', NULL, NULL, NULL),
            ('SD', 'de', 'Sudan', 0, '00', NULL, NULL, NULL),
            ('SE', 'de', 'Schweden', 0, '00', NULL, NULL, NULL),
            ('SG', 'de', 'Singapur', 0, '00', NULL, NULL, NULL),
            ('SH', 'de', 'St. Helena', 0, '00', NULL, NULL, NULL),
            ('SI', 'de', 'Slowenien', 0, '00', NULL, NULL, NULL),
            ('SJ', 'de', 'Svalbard und Jan Mayen', 0, '00', NULL, NULL, NULL),
            ('SK', 'de', 'Slowakei', 0, '00', NULL, NULL, NULL),
            ('SL', 'de', 'Sierra Leone', 0, '00', NULL, NULL, NULL),
            ('SM', 'de', 'San Marino', 0, '00', NULL, NULL, NULL),
            ('SN', 'de', 'Senegal', 0, '00', NULL, NULL, NULL),
            ('SO', 'de', 'Somalia', 0, '00', NULL, NULL, NULL),
            ('SR', 'de', 'Suriname', 0, '00', NULL, NULL, NULL),
            ('ST', 'de', 'São Tomé und Príncipe', 0, '00', NULL, NULL, NULL),
            ('SV', 'de', 'El Salvador', 0, '00', NULL, NULL, NULL),
            ('SY', 'de', 'Syrien', 0, '00', NULL, NULL, NULL),
            ('SZ', 'de', 'Swasiland', 0, '00', NULL, NULL, NULL),
            ('TC', 'de', 'Turks- und Caicosinseln', 0, '00', NULL, NULL, NULL),
            ('TD', 'de', 'Tschad', 0, '00', NULL, NULL, NULL),
            ('TF', 'de', 'Französische Süd- und Antarktisgebiete', 0, '00', NULL, NULL, NULL),
            ('TG', 'de', 'Togo', 0, '00', NULL, NULL, NULL),
            ('TH', 'de', 'Thailand', 0, '00', NULL, NULL, NULL),
            ('TJ', 'de', 'Tadschikistan', 0, '00', NULL, NULL, NULL),
            ('TK', 'de', 'Tokelau', 0, '00', NULL, NULL, NULL),
            ('TL', 'de', 'Osttimor', 0, '00', NULL, NULL, NULL),
            ('TM', 'de', 'Turkmenistan', 0, '00', NULL, NULL, NULL),
            ('TN', 'de', 'Tunesien', 0, '00', NULL, NULL, NULL),
            ('TO', 'de', 'Tonga', 0, '00', NULL, NULL, NULL),
            ('TR', 'de', 'Türkei', 0, '00', NULL, NULL, NULL),
            ('TT', 'de', 'Trinidad und Tobago', 0, '00', NULL, NULL, NULL),
            ('TV', 'de', 'Tuvalu', 0, '00', NULL, NULL, NULL),
            ('TW', 'de', 'Taiwan', 0, '00', NULL, NULL, NULL),
            ('TZ', 'de', 'Tansania', 0, '00', NULL, NULL, NULL),
            ('UA', 'de', 'Ukraine', 0, '00', NULL, NULL, NULL),
            ('UG', 'de', 'Uganda', 0, '00', NULL, NULL, NULL),
            ('UM', 'de', 'Amerikanisch-Ozeanien', 0, '00', NULL, NULL, NULL),
            ('US', 'de', 'Vereinigte Staaten', 0, '00', NULL, NULL, NULL),
            ('UY', 'de', 'Uruguay', 0, '00', NULL, NULL, NULL),
            ('UZ', 'de', 'Usbekistan', 0, '00', NULL, NULL, NULL),
            ('VA', 'de', 'Vatikanstadt', 0, '00', NULL, NULL, NULL),
            ('VC', 'de', 'St. Vincent und die Grenadinen', 0, '00', NULL, NULL, NULL),
            ('VE', 'de', 'Venezuela', 0, '00', NULL, NULL, NULL),
            ('VG', 'de', 'Britische Jungferninseln', 0, '00', NULL, NULL, NULL),
            ('VI', 'de', 'Amerikanische Jungferninseln', 0, '00', NULL, NULL, NULL),
            ('VN', 'de', 'Vietnam', 0, '00', NULL, NULL, NULL),
            ('VU', 'de', 'Vanuatu', 0, '00', NULL, NULL, NULL),
            ('WF', 'de', 'Wallis und Futuna', 0, '00', NULL, NULL, NULL),
            ('WS', 'de', 'Samoa', 0, '00', NULL, NULL, NULL),
            ('YE', 'de', 'Jemen', 0, '00', NULL, NULL, NULL),
            ('YT', 'de', 'Mayotte', 0, '00', NULL, NULL, NULL),
            ('ZA', 'de', 'Südafrika', 0, '00', NULL, NULL, NULL),
            ('ZM', 'de', 'Sambia', 0, '00', NULL, NULL, NULL),
            ('ZW', 'de', 'Simbabwe', 0, '00', NULL, NULL, NULL),
            ('ZZ', 'de', 'Unbekannte oder ungültige Region', 0, '00', NULL, NULL, NULL);"));
        
    }
}

/*
 * Command to run:
 * php artisan db:seed --class="CoutryTableSeeder"
 */