<?php
class ResourceTableSeeder extends Seeder {

    public function run()
    {
        DB::insert(DB::raw("INSERT INTO `001_007_resource` (`id_007`, `name_007`, `package_007`) VALUES
            ('pulsar',                          'Pulsar',                           1),
            ('admin',                           'Package de administración',        2),
            ('admin-country',                   'Paises',                           2),
            ('admin-country-at1',               'Paises -- Áreas territoriales 1',  2),
            ('admin-country-at2',               'Paises -- Áreas territoriales 2',  2),
            ('admin-country-at3',               'Paises -- Áreas territoriales 3',  2),
            ('admin-cron',                      'Tareas Cron',                      2),
            ('admin-google-services',           'Google Services',                  2),
            ('admin-lang',                      'Idiomas',                          2),
            ('admin-packages',                  'Packages',                         2),
            ('admin-perm',                      'Sección Permisos',                 2),
            ('admin-perm-actions',              'Permisos -- Acciones',             2),
            ('admin-perm-perm',                 'Permisos -- Permisos',             2),
            ('admin-perm-profile',              'Permisos -- Perfiles',             2),
            ('admin-perm-resource',             'Permisos -- Recursos',             2),
            ('admin-socials',                   'Redes sociales',                   2),
            ('admin-user',                      'Usuarios',                         2),
            ('cabinas',                         'Reservas de Cabinas',              4),
            ('cabinas-cabinas',                 'Cabinas',                          4),
            ('cabinas-citas',                   'Citas',                            4),
            ('cabinas-esteticistas',            'Esteticistas',                     4),
            ('cabinas-horarios',                'Horarios',                         4),
            ('cabinas-locales',                 'Locales',                          4),
            ('cabinas-preferencias',            'Preferencias',                     4),
            ('cabinas-tratamientos',            'Tratamientos',                     4),
            ('comunik',                         'Package Comunik',                  5),
            ('comunik-contacts',                'Contactos',                        5),
            ('comunik-groups',                  'Grupos',                           5),
            ('comunik-email-campaigns',         'Email services -- Campañas',       5),
            ('comunik-email-sendings',          'Email services -- Envíos',         5),
            ('comunik-email-accounts',          'Email services -- Cuentas',        5),
            ('comunik-email-templates',         'Email services -- Plantillas',     5),
            ('comunik-email-preferences',       'Email services -- Preferencias',   5),
            ('comunik-email-messages',          'Email services -- Mensajes',       5),
            ('comunik-email-patterns',          'Email services -- Patrones',       5),
            ('comunik-sms-campaigns',           'SMS services -- Campañas',         5),
            ('comunik-sms-templates',           'SMS services -- Plantillas',       5),
            ('comunik-sms-senders',             'SMS services -- Remitentes',       5),
            ('comunik-sms-preferences',         'SMS services -- Preferencias',     5),
            ('updater',                         'Updater',                          6),
            ('updater-projects',                'Projects',                         6),
            ('updater-deployments',             'Deployments',                      6),
            ('updater-updates',                 'Updates',                          6),
            ('vinipad',                         'Vinipad',                          3),
            ('vinipad-activaciones',            'Activaciones',                     3),
            ('vinipad-clientes',                'Clientes',                         3),
            ('vinipad-locales',                 'Locales',                          3),
            ('vinipad-systems',                 'Sistemas',                         3),
            ('vinipadcc',                       'Módulo Vinipad Cuaderno de Cata',  9),
            ('vinipadcc-bodegas',               'Bodegas',                          9),
            ('vinipadcc-do',                    'D.O.',                             9),
            ('vinipadcc-maridajes',             'Maridajes',                        9),
            ('vinipadcc-tipos',                 'Tipos',                            9),
            ('vinipadcc-uvas',                  'Uvas',                             9),
            ('vinipadcc-vinos',                 'Vinos',                            9),
            ('vinipadsalesforce',               'Módulo Vinipad Sales Force',       7),
            ('vinipadsalesforce-perfiles',      'Perfiles',                         7),
            ('vinipadsalesforce-preferencias',  'Preferencias',                     7),
            ('vinipadsalesforce-proveedores',   'Proveedores',                      7),
            ('vinipadsalesforce-usuarios',      'Usuarios',                         7),
            ('vinipadsf-frontend',              'Módulo Vinipad Sales Force',       8),
            ('vinipadsf-frontend-alarmas',      'Alarmas',                          8),
            ('vinipadsf-frontend-locales',      'Locales',                          8),
            ('vinipadsf-frontend-notificacio',  'Notificaciones',                   8),
            ('vinipadsf-frontend-usuarios',     'Usuarios',                         8),
            ('soportespub',                     'Soportes Publicitarios',           10),
            ('soportespub-familias',            'Familias',                         10),
            ('soportespub-empresas',            'Empresas',                         10),
            ('soportespub-laboratorios',        'Laboratorios',                     10),
            ('soportespub-marcas',              'Marcas',                           10),
            ('soportespub-preferencias',        'Preferencias',                     10),
            ('soportespub-productos',           'Productos',                        10),
            ('soportespub-clientes',            'Clientes',                         10),
            ('soportespub-puntosventa',         'Puntos de venta',                  10),
            ('soportespub-solicitudes',         'Solicitudes',                      10),
            ('hotels',                          'Hotels',                           13),
            ('hotels-atenciones',               'Hotels',                           13),
            ('hotels-decoraciones',             'Hotels',                           13),
            ('hotels-entornos',                 'Hotels',                           13);"));
    }
}

/*
 * Command to run:
 * php artisan db:seed --class="ResourceTableSeeder"
 */