<?php
class TerritorialArea1TableSeeder extends Seeder
{
    public function run()
    {   
        
        //DATA 001_003_territorial_area_1 (BR)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('BR-AC', 'BR', 'Acre'),
            ('BR-AL', 'BR', 'Alagoas'),
            ('BR-AM', 'BR', 'Amazonas'),
            ('BR-AP', 'BR', 'Amapá'),
            ('BR-BA', 'BR', 'Bahia'),
            ('BR-CE', 'BR', 'Ceará'),
            ('BR-DF', 'BR', 'Distrito Federal'),
            ('BR-ES', 'BR', 'Espírito Santo'),
            ('BR-GO', 'BR', 'Goiás'),
            ('BR-MA', 'BR', 'Maranhão'),
            ('BR-MG', 'BR', 'Minas Gerais'),
            ('BR-MS', 'BR', 'Mato Grosso do Sul'),
            ('BR-MT', 'BR', 'Mato Grosso'),
            ('BR-PA', 'BR', 'Pará'),
            ('BR-PB', 'BR', 'Paraíba'),
            ('BR-PE', 'BR', 'Pernambuco'),
            ('BR-PI', 'BR', 'Piauí'),
            ('BR-PR', 'BR', 'Paraná'),
            ('BR-RJ', 'BR', 'Río de Janeiro'),
            ('BR-RN', 'BR', 'Rio Grande do Norte'),
            ('BR-RO', 'BR', 'Rondônia'),
            ('BR-RR', 'BR', 'Roraima'),
            ('BR-RS', 'BR', 'Rio Grande do Sul'),
            ('BR-SC', 'BR', 'Santa Catarina'),
            ('BR-SE', 'BR', 'Sergipe'),
            ('BR-SP', 'BR', 'São Paulo'),
            ('BR-TO', 'BR', 'Tocantins');"));
        
        //DATA 001_003_territorial_area_1 (CA)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('CA-AB', 'CA', 'Alberta'),
            ('CA-BC', 'CA', 'British Columbia'),
            ('CA-MB', 'CA', 'Manitoba'),
            ('CA-NB', 'CA', 'New Brunswick'),
            ('CA-NL', 'CA', 'Newfoundland and Labrador'),
            ('CA-NS', 'CA', 'Nova Scotia'),
            ('CA-ON', 'CA', 'Ontario'),
            ('CA-PE', 'CA', 'Prince Edward Island'),
            ('CA-QC', 'CA', 'Quebec'),
            ('CA-SK', 'CA', 'Saskatchewan'),
            ('CA-NT', 'CA', 'Northwest Territories'),
            ('CA-NU', 'CA', 'Nunavut'),
            ('CA-YT', 'CA', 'Yukon Territory');"));
        
        //DATA 001_003_territorial_area_1 (ZH)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('CH-AG', 'CH', 'Argovia'),
            ('CH-AI', 'CH', 'Appezell Rodas Interiores'),
            ('CH-AR', 'CH', 'Appenzell Rodas Exteriores'),
            ('CH-BE', 'CH', 'Berna'),
            ('CH-BL', 'CH', 'Basilea-Campiña'),
            ('CH-BS', 'CH', 'Basilea-Ciudad'),
            ('CH-FR', 'CH', 'Friburgo'),
            ('CH-GE', 'CH', 'Ginebra'),
            ('CH-GL', 'CH', 'Glaris'),
            ('CH-GR', 'CH', 'Grisones'),
            ('CH-JU', 'CH', 'Jura'),
            ('CH-LU', 'CH', 'Lucerna'),
            ('CH-NE', 'CH', 'Neuchâtel'),
            ('CH-NW', 'CH', 'Nidwalden'),
            ('CH-OW', 'CH', 'Obwalden'),
            ('CH-SG', 'CH', 'San Galo'),
            ('CH-SH', 'CH', 'Schaffhausen'),
            ('CH-SO', 'CH', 'Soleura'),
            ('CH-SZ', 'CH', 'Schwyz'),
            ('CH-TG', 'CH', 'Turgovia'),
            ('CH-TI', 'CH', 'Tesino'),
            ('CH-UR', 'CH', 'Uri'),
            ('CH-VD', 'CH', 'Vaud'),
            ('CH-VS', 'CH', 'Valais'),
            ('CH-ZG', 'CH', 'Zug'),
            ('CH-ZH', 'CH', 'Zúrich');"));
        
        //DATA 001_003_territorial_area_1 (CO)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('CO-DC', 'CO', 'Bogotá'),
            ('CO-AN', 'CO', 'Antioquia'),
            ('CO-AR', 'CO', 'Arauca'),
            ('CO-AT', 'CO', 'Atlántico'),
            ('CO-BO', 'CO', 'Bolívar'),
            ('CO-BY', 'CO', 'Boyacá'),
            ('CO-CA', 'CO', 'Caldas'),
            ('CO-CQ', 'CO', 'Caquetá'),
            ('CO-CS', 'CO', 'Casanare'),
            ('CO-CC', 'CO', 'Cauca'),
            ('CO-CE', 'CO', 'Cesar'),
            ('CO-CH', 'CO', 'Chocó'),
            ('CO-CO', 'CO', 'Córdoba'),
            ('CO-CU', 'CO', 'Cundinamarca'),
            ('CO-GU', 'CO', 'Guainía'),
            ('CO-GV', 'CO', 'Guaviare'),
            ('CO-HU', 'CO', 'Huila'),
            ('CO-LA', 'CO', 'La Guajira'),
            ('CO-MA', 'CO', 'Magdalena'),
            ('CO-ME', 'CO', 'Meta'),
            ('CO-NA', 'CO', 'Nariño'),
            ('CO-NS', 'CO', 'Norte de Santander'),
            ('CO-PU', 'CO', 'Putumayo'),
            ('CO-QU', 'CO', 'Quindío'),
            ('CO-RI', 'CO', 'Risaralda'),
            ('CO-SA', 'CO', 'San Andrés y Providencia'),
            ('CO-SN', 'CO', 'Santander'),
            ('CO-SU', 'CO', 'Sucre'),
            ('CO-TO', 'CO', 'Tolima'),
            ('CO-VA', 'CO', 'Valle del Cauca'),
            ('CO-VU', 'CO', 'Vaupés'),
            ('CO-VI', 'CO', 'Vichada');"));

        //DATA 001_003_territorial_area_1 (CO)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('CR-A',  'CR', 'Alajuela'),
            ('CR-C',  'CR', 'Cartago'),
            ('CR-G',  'CR', 'Guanacaste'),
            ('CR-H',  'CR', 'Heredia'),
            ('CR-L',  'CR', 'Limón'),
            ('CR-P',  'CR', 'Puntarenas'),
            ('CR-SJ', 'CR', 'San José');"));
        
        //DATA 001_003_territorial_area_1 (EC)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('EC-A', 'EC', 'Azuay'),
            ('EC-B', 'EC', 'Bolívar'),
            ('EC-F', 'EC', 'Cañar'),
            ('EC-C', 'EC', 'Carchi'),
            ('EC-H', 'EC', 'Chimborazo'),
            ('EC-X', 'EC', 'Cotopaxi'),
            ('EC-O', 'EC', 'El Oro'),
            ('EC-E', 'EC', 'Esmeraldas'),
            ('EC-W', 'EC', 'Galápagos'),
            ('EC-G', 'EC', 'Guayas'),
            ('EC-I', 'EC', 'Imbabura'),
            ('EC-L', 'EC', 'Loja'),
            ('EC-R', 'EC', 'Los Ríos'),
            ('EC-M', 'EC', 'Manabí'),
            ('EC-S', 'EC', 'Morona Santiago'),
            ('EC-N', 'EC', 'Napo'),
            ('EC-D', 'EC', 'Orellana'),
            ('EC-Y', 'EC', 'Pastaza'),
            ('EC-P', 'EC', 'Pichincha'),
            ('EC-SE', 'EC', 'Santa Elena'),
            ('EC-SD', 'EC', 'Santo Domingo de los Tsáchilas'),
            ('EC-U', 'EC', 'Sucumbíos'),
            ('EC-T', 'EC', 'Tungurahua'),
            ('EC-Z', 'EC', 'Zamora Chinchipe');"));

        //DATA 001_003_territorial_area_1 (ES)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('ES-AN', 'ES', 'Andalucía'),
            ('ES-AR', 'ES', 'Aragón'),
            ('ES-AS', 'ES', 'Principado de Asturias'),
            ('ES-CB', 'ES', 'Cantabria'),
            ('ES-CE', 'ES', 'Ceuta'),
            ('ES-CL', 'ES', 'Castilla y León'),
            ('ES-CM', 'ES', 'Castilla-La Mancha'),
            ('ES-CN', 'ES', 'Islas Canarias'),
            ('ES-CT', 'ES', 'Cataluña'),
            ('ES-EX', 'ES', 'Extremadura'),
            ('ES-GA', 'ES', 'Galicia'),
            ('ES-IB', 'ES', 'Islas Baleares'),
            ('ES-MC', 'ES', 'Región de Murcia'),
            ('ES-MD', 'ES', 'Comunidad de Madrid'),
            ('ES-ML', 'ES', 'Melilla'),
            ('ES-NC', 'ES', 'Comunidad Foral de Navarra'),
            ('ES-PV', 'ES', 'País Vasco'),
            ('ES-RI', 'ES', 'La Rioja'),
            ('ES-VC', 'ES', 'Comunidad Valenciana');"));
        
        //DATA 001_003_territorial_area_1 (GT)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('GT-AV', 'GT', 'Alta Verapaz'),
            ('GT-BV', 'GT', 'Baja Verapaz'),
            ('GT-CM', 'GT', 'Chimaltenango'),
            ('GT-CQ', 'GT', 'Chiquimula'),
            ('GT-PR', 'GT', 'El Progreso'),
            ('GT-ES', 'GT', 'Escuintla'),
            ('GT-GU', 'GT', 'Guatemala'),
            ('GT-HU', 'GT', 'Huehuetenango'),
            ('GT-IZ', 'GT', 'Izabal'),
            ('GT-JA', 'GT', 'Jalapa'),
            ('GT-JU', 'GT', 'Jutiapa'),
            ('GT-PE', 'GT', 'Petén'),
            ('GT-QZ', 'GT', 'Quetzaltenango'),
            ('GT-QC', 'GT', 'Quiché'),
            ('GT-RE', 'GT', 'Retalhuleu'),
            ('GT-SA', 'GT', 'Sacatepéquez'),
            ('GT-SM', 'GT', 'San Marcos'),
            ('GT-SR', 'GT', 'Santa Rosa'),
            ('GT-SO', 'GT', 'Sololá'),
            ('GT-SU', 'GT', 'Suchitepéquez'),
            ('GT-TO', 'GT', 'Totonicapán'),
            ('GT-ZA', 'GT', 'Zacapa');"));
        
        //DATA 001_003_territorial_area_1 (MX)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('MX-AG', 'MX', 'Aguascalientes'),
            ('MX-BC', 'MX', 'Baja California'),
            ('MX-BS', 'MX', 'Baja California Sur'),
            ('MX-CM', 'MX', 'Campeche'),
            ('MX-CS', 'MX', 'Chiapas'),
            ('MX-CH', 'MX', 'Chihuahua'),
            ('MX-CO', 'MX', 'Coahuila'),
            ('MX-CL', 'MX', 'Colima'),
            ('MX-DF', 'MX', 'Distrito Federal'),
            ('MX-DG', 'MX', 'Durango'),
            ('MX-GT', 'MX', 'Guanajuato'),
            ('MX-GR', 'MX', 'Guerrero'),
            ('MX-HG', 'MX', 'Hidalgo'),
            ('MX-JC', 'MX', 'Jalisco'),
            ('MX-ME', 'MX', 'Estado de México'),
            ('MX-MN', 'MX', 'Michoacán'),
            ('MX-MS', 'MX', 'Morelos'),
            ('MX-NT', 'MX', 'Nayarit'),
            ('MX-NL', 'MX', 'Nuevo León'),
            ('MX-OC', 'MX', 'Oaxaca'),
            ('MX-PL', 'MX', 'Puebla'),
            ('MX-QO', 'MX', 'Querétaro'),
            ('MX-QR', 'MX', 'Quintana Roo'),
            ('MX-SP', 'MX', 'San Luis Potosí'),
            ('MX-SL', 'MX', 'Sinaloa'),
            ('MX-SR', 'MX', 'Sonora'),
            ('MX-TC', 'MX', 'Tabasco'),
            ('MX-TS', 'MX', 'Tamaulipas'),
            ('MX-TL', 'MX', 'Tlaxcala'),
            ('MX-VZ', 'MX', 'Veracruz'),
            ('MX-YN', 'MX', 'Yucatán'),
            ('MX-ZS', 'MX', 'Zacatecas');"));
        
        //DATA 001_003_territorial_area_1 (PT)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('PT-AC', 'PT', 'Açores'),
            ('PT-AV', 'PT', 'Aveiro'),
            ('PT-BE', 'PT', 'Beja'),
            ('PT-BR', 'PT', 'Braga'),
            ('PT-BA', 'PT', 'Bragança'),
            ('PT-CB', 'PT', 'Castelo Branco'),
            ('PT-CO', 'PT', 'Coimbra'),
            ('PT-EV', 'PT', 'Évora'),
            ('PT-FA', 'PT', 'Faro'),
            ('PT-GU', 'PT', 'Guarda'),
            ('PT-LE', 'PT', 'Leiria'),
            ('PT-LI', 'PT', 'Lisboa'),
            ('PT-MA', 'PT', 'Madeira'),
            ('PT-PA', 'PT', 'Portalegre'),
            ('PT-PO', 'PT', 'Porto'),
            ('PT-SA', 'PT', 'Santarém'),
            ('PT-SE', 'PT', 'Setúbal'),
            ('PT-VC', 'PT', 'Viana do Castelo'),
            ('PT-VR', 'PT', 'Vila Real'),
            ('PT-VI', 'PT', 'Viseu');"));
        
        //DATA 001_003_territorial_area_1 (TH)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('TH-10', 'TH', 'Bangkok'),
            ('TH-S', 'TH', 'Pattaya'),
            ('TH-37', 'TH', 'Amnat Charoen'),
            ('TH-15', 'TH', 'Ang Thong'),
            ('TH-31', 'TH', 'Buri Ram'),
            ('TH-24', 'TH', 'Chachoengsao'),
            ('TH-18', 'TH', 'Chai Nat'),
            ('TH-36', 'TH', 'Chaiyaphum'),
            ('TH-22', 'TH', 'Chanthaburi'),
            ('TH-50', 'TH', 'Chiang Mai'),
            ('TH-57', 'TH', 'Chiang Rai'),
            ('TH-20', 'TH', 'Chon Buri'),
            ('TH-86', 'TH', 'Chumphon'),
            ('TH-46', 'TH', 'Kalasin'),
            ('TH-62', 'TH', 'Kamphaeng Phet'),
            ('TH-71', 'TH', 'Kanchanaburi'),
            ('TH-40', 'TH', 'Khon Kaen'),
            ('TH-81', 'TH', 'Krabi'),
            ('TH-52', 'TH', 'Lampang'),
            ('TH-51', 'TH', 'Lamphun'),
            ('TH-42', 'TH', 'Loei'),
            ('TH-16', 'TH', 'Lop Buri'),
            ('TH-58', 'TH', 'Mae Hong Son'),
            ('TH-44', 'TH', 'Maha Sarakham'),
            ('TH-49', 'TH', 'Mukdahan'),
            ('TH-26', 'TH', 'Nakhon Nayok'),
            ('TH-73', 'TH', 'Nakhon Pathom'),
            ('TH-48', 'TH', 'Nakhon Phanom'),
            ('TH-30', 'TH', 'Nakhon Ratchasima'),
            ('TH-60', 'TH', 'Nakhon Sawan'),
            ('TH-80', 'TH', 'Nakhon Si Thammarat'),
            ('TH-55', 'TH', 'Nan'),
            ('TH-96', 'TH', 'Narathiwat'),
            ('TH-39', 'TH', 'Nong Bua Lam Phu'),
            ('TH-43', 'TH', 'Nong Khai'),
            ('TH-12', 'TH', 'Nonthaburi'),
            ('TH-13', 'TH', 'Pathum Thani'),
            ('TH-94', 'TH', 'Pattani'),
            ('TH-82', 'TH', 'Phangnga'),
            ('TH-93', 'TH', 'Phatthalung'),
            ('TH-56', 'TH', 'Phayao'),
            ('TH-67', 'TH', 'Phetchabun'),
            ('TH-76', 'TH', 'Phetchaburi'),
            ('TH-66', 'TH', 'Phichit'),
            ('TH-65', 'TH', 'Phitsanulok'),
            ('TH-54', 'TH', 'Phrae'),
            ('TH-14', 'TH', 'Phra Nakhon Si Ayutthaya'),
            ('TH-83', 'TH', 'Phuket'),
            ('TH-25', 'TH', 'Prachin Buri'),
            ('TH-77', 'TH', 'Prachuap Khiri Khan'),
            ('TH-85', 'TH', 'Ranong'),
            ('TH-70', 'TH', 'Ratchaburi'),
            ('TH-21', 'TH', 'Rayong'),
            ('TH-45', 'TH', 'Roi Et'),
            ('TH-27', 'TH', 'Sa Kaeo'),
            ('TH-47', 'TH', 'Sakon Nakhon'),
            ('TH-11', 'TH', 'Samut Prakan'),
            ('TH-74', 'TH', 'Samut Sakhon'),
            ('TH-75', 'TH', 'Samut Songkhram'),
            ('TH-19', 'TH', 'Saraburi'),
            ('TH-91', 'TH', 'Satun'),
            ('TH-17', 'TH', 'Sing Buri'),
            ('TH-33', 'TH', 'Si Sa Ket'),
            ('TH-90', 'TH', 'Songkhla'),
            ('TH-64', 'TH', 'Sukhothai'),
            ('TH-72', 'TH', 'Suphan Buri'),
            ('TH-84', 'TH', 'Surat Thani'),
            ('TH-32', 'TH', 'Surin'),
            ('TH-63', 'TH', 'Tak'),
            ('TH-92', 'TH', 'Trang'),
            ('TH-23', 'TH', 'Trat'),
            ('TH-34', 'TH', 'Ubon Ratchathani'),
            ('TH-41', 'TH', 'Udon Thani'),
            ('TH-61', 'TH', 'Uthai Thani'),
            ('TH-53', 'TH', 'Uttaradit'),
            ('TH-95', 'TH', 'Yala'),
            ('TH-35', 'TH', 'Yasothon');"));
        
        //DATA 001_003_territorial_area_1 (US)
        DB::insert(DB::raw("INSERT INTO `001_003_territorial_area_1` (`id_003`, `country_003`, `name_003`) VALUES
            ('US-AL', 'US', 'Alabama'),
            ('US-AK', 'US', 'Alaska'),
            ('US-AZ', 'US', 'Arizona'),
            ('US-AR', 'US', 'Arkansas'),
            ('US-CA', 'US', 'California'),
            ('US-CO', 'US', 'Colorado'),
            ('US-CT', 'US', 'Connecticut'),
            ('US-DE', 'US', 'Delaware'),
            ('US-FL', 'US', 'Florida'),
            ('US-GA', 'US', 'Georgia'),
            ('US-HI', 'US', 'Hawaii'),
            ('US-ID', 'US', 'Idaho'),
            ('US-IL', 'US', 'Illinois'),
            ('US-IN', 'US', 'Indiana'),
            ('US-IA', 'US', 'Iowa'),
            ('US-KS', 'US', 'Kansas'),
            ('US-KY', 'US', 'Kentucky'),
            ('US-LA', 'US', 'Louisiana'),
            ('US-ME', 'US', 'Maine'),
            ('US-MD', 'US', 'Maryland'),
            ('US-MA', 'US', 'Massachusetts'),
            ('US-MI', 'US', 'Michigan'),
            ('US-MN', 'US', 'Minnesota'),
            ('US-MS', 'US', 'Mississippi'),
            ('US-MO', 'US', 'Missouri'),
            ('US-MT', 'US', 'Montana'),
            ('US-NE', 'US', 'Nebraska'),
            ('US-NV', 'US', 'Nevada'),
            ('US-NH', 'US', 'New Hampshire'),
            ('US-NJ', 'US', 'New Jersey'),
            ('US-NM', 'US', 'New Mexico'),
            ('US-NY', 'US', 'New York'),
            ('US-NC', 'US', 'North Carolina'),
            ('US-ND', 'US', 'North Dakota'),
            ('US-OH', 'US', 'Ohio'),
            ('US-OK', 'US', 'Oklahoma'),
            ('US-OR', 'US', 'Oregon'),
            ('US-PA', 'US', 'Pennsylvania'),
            ('US-RI', 'US', 'Rhode Island'),
            ('US-SC', 'US', 'South Carolina'),
            ('US-SD', 'US', 'South Dakota'),
            ('US-TN', 'US', 'Tennessee'),
            ('US-TX', 'US', 'Texas'),
            ('US-UT', 'US', 'Utah'),
            ('US-VT', 'US', 'Vermont'),
            ('US-VA', 'US', 'Virginia'),
            ('US-WA', 'US', 'Washington'),
            ('US-WV', 'US', 'West Virginia'),
            ('US-WI', 'US', 'Wisconsin'),
            ('US-WY', 'US', 'Wyoming'),
            ('US-DC', 'US', 'District of Columbia');"));

    }
}
/*
 * Command to run:
 * php artisan db:seed --class="TerritorialArea1TableSeeder"
 */