@extends('pulsar::layouts.form', ['action' => 'store'])

@section('rows')
    <!-- pulsar::field.create -->
    @include('pulsar::includes.html.form_text_group', ['label' => 'ID', 'name' => 'id',  'value' => Input::old('name', isset($object->id_026)? $object->id_026 : null), 'readOnly' => true, 'fieldSize' => 2])
    @include('pulsar::includes.html.form_select_group', ['label' => trans_choice('pulsar::pulsar.family', 1), 'name' => 'family', 'value' => Input::old('famlily'), 'required' => true, 'objects' => $families, 'idSelect' => 'id_025', 'nameSelect' => 'name_025', 'class' => 'form-control select2', 'fieldSize' => 5, 'data' => ['language' => config('app.locale'), 'width' => '100%', 'error-placement' => 'select2-section-outer-container', 'disabled' => isset($object->id_025)? true : null]])
    @include('pulsar::includes.html.form_image_group', ['label' => trans_choice('pulsar::pulsar.language', 1), 'name' => 'lang', 'nameImage' => $lang->name_001, 'value' => $lang->id_001, 'url' => asset('/packages/syscover/pulsar/storage/langs/' . $lang->image_001)])
    @include('pulsar::includes.html.form_text_group', ['label' => trans_choice('pulsar::pulsar.label', 1), 'name' => 'label', 'value' => Input::old('name', isset($object->label_026)? $object->label_026 : null), 'maxLength' => '100', 'rangeLength' => '2,100', 'required' => true])
    @include('pulsar::includes.html.form_text_group', ['label' => trans('pulsar::pulsar.name'), 'name' => 'name', 'value' => Input::old('name', isset($object->name_026)? $object->name_026 : null), 'maxLength' => '100', 'rangeLength' => '2,100', 'required' => true, 'readOnly' => isset($object->id_026)])
    @include('pulsar::includes.html.form_checkbox_group', ['label' => trans('pulsar::pulsar.int_value'), 'name' => 'intValue', 'value' => 1, 'checked' => Input::old('intValue',  isset($object)? $object->int_value_026 : null)])
    @include('pulsar::includes.html.form_checkbox_group', ['label' => trans('pulsar::pulsar.required'), 'name' => 'required', 'value' => 1, 'checked' => Input::old('required',  isset($object)? $object->required_026 : null)])
    @include('pulsar::includes.html.form_text_group', ['label' => trans('pulsar::pulsar.sorting'), 'name' => 'sorting', 'type' => 'number', 'value' => Input::old('sorting', isset($object->sorting_026)? $object->sorting_026 : null), 'maxLength' => '3', 'rangeLength' => '1,3', 'min' => '0', 'fieldSize' => 2])
    @include('pulsar::includes.html.form_text_group', ['label' => trans('pulsar::pulsar.maximum_length'), 'name' => 'maxLength', 'type' => 'number', 'value' => Input::old('maxLength', isset($object->max_length_026)? $object->max_length_026 : null), 'maxLength' => '3', 'rangeLength' => '1,3', 'min' => '0', 'fieldSize' => 2])
    @include('pulsar::includes.html.form_text_group', ['label' => trans('pulsar::pulsar.pattern'), 'name' => 'pattern', 'value' => Input::old('pattern', isset($object->pattern_026)? $object->pattern_026 : null), 'maxLength' => '50', 'rangeLength' => '2,50', 'fieldSize' => 5, 'readOnly' => isset($object->id_026)])
    @include('pulsar::includes.html.form_text_group', ['label' => trans('pulsar::pulsar.label_size'), 'name' => 'labelSize', 'type' => 'number', 'value' => Input::old('labelSize', isset($object->label_size_026)? $object->label_size_026 : null), 'maxLength' => '1', 'min' => '0', 'fieldSize' => 2, 'inputs' =>[
        ['label' => trans('pulsar::pulsar.field_size'), 'name' => 'fieldSize', 'type' => 'number', 'value' => Input::old('fieldSize', isset($object->field_size_026)? $object->field_size_026 : null), 'maxLength' => '1', 'min' => '0', 'fieldSize' => 2]
    ]])
    <!-- /pulsar::field.create -->
@stop